### ISSUE TITLE
Unrecognized character "windows" when trying to set command hotkey

### ISSUE THREAD

**Issue by DZGoldman** [boppreh/keyboard#105]
`keyboard.add_hotkey('win+t', lambda: keyboard.write('test'))`
gives 
```
 File "...keyboard/_darwinkeyboard.py", line 153, in character_to_vk
    raise ValueError("Unrecognized character: {}".format(character))
ValueError: Unrecognized character: windows
```
whenever I press a key.

And `keyboard.all_modifers` shows 
```('alt', 'alt gr', 'ctrl', 'shift', 'win')```
which suggests `win` should be the valid key for the command key.

**Comment by boppreh** [comment]
Thanks for the bug report.

This is being worked on in this pull request: https://github.com/boppreh/keyboard/issues/105

**Comment by DZGoldman** [comment]
Ah, thanks!

**Comment by glitchassassin** [comment]
This should now be resolved, I believe.
