### ISSUE TITLE
Japanese keyboard layouts cause segfault in _darwinkeyboard.py

### ISSUE THREAD

**Issue by matomatical** [boppreh/keyboard#108]
Line number 126 of _darwinkeyboard.py (current master branch):
```python
# Get keyboard layout
klis = Carbon.TISCopyCurrentKeyboardInputSource()
k_layout = Carbon.TISGetInputSourceProperty(klis, kTISPropertyUnicodeKeyLayoutData)
k_layout_size = Carbon.CFDataGetLength(k_layout)
# ^-- THIS ONE
```
causes a segfault when I try to `import keyboard` on macOS with my input source set to Japanese (in all input modes). It goes away when I try to import with a different input source active (such as Australian, Greek, or Unicode Hex Input).

I wanted to investigate further but I am not familiar with ctypes or the Carbon library, sorry. Thought I'd raise this issue since support for internationalized layouts was mentioned as a goal in #11.

**Comment by glitchassassin** [comment]
Looks like TISGetInputSourceProperty returns null on Japanese keyboard layouts, hence the crash:

https://github.com/Microsoft/vscode/issues/23833#issuecomment-291366154

This thread suggests using TISCopyCurrentKeyboardLayoutInputSource as a fallback if that doesn't work.

**Comment by haoflynet** [comment]
Could I push a pull request for this bug? I fix it on https://github.com/moses-palmer/pynput/pull/58 last week.

**Comment by glitchassassin** [comment]
Should be resolved in master branch (thanks @haoflynet!). @matomatical, can you confirm?

**Comment by matomatical** [comment]
Swell. Confirmed: no more segfault. Thank you.
