### ISSUE TITLE
Issues with function keys+modifiers

### ISSUE THREAD

**Issue by atribecalledkwest** [boppreh/keyboard#114]
I recently wrote a utility using this library that's meant to integrate with twitch. To try and not interfere with other keybinds, I was using the F13-24 keys with modifiers with a custom keyboard. However, this library seems to not really handle these well at all.

Test:
```python
import keyboard
tests = ["f11", "f12", "shift+f11", "shift+f12"]
for key in tests:
    keyboard.add_hotkey(key, lambda: print(key))
keyboard.wait()
```

Expected result:
Pressing f12 should trigger the f12 hook, pressing shift+f12 triggers the shift+f12 hook
Actual result:
Pressing f11 or f12 triggers the shift+f12 hook.

It seems to just trigger the last keybind that was added in further testing. Am I doing something wrong?

All this was run on Windows 10 using Python 2.7.14.

**Comment by boppreh** [comment]
I think you've been hit by a problem in Python itself. The "key" variable is the same across all loops, so the print inside the lambda is printing the last value.

Try "lambda key=key: print(key)" and see if it fixes the problem.

For more information: https://stackoverflow.com/questions/2295290/what-do-lambda-function-closures-capture

**Comment by atribecalledkwest** [comment]
Yes, thank you! Silly oversight.
