### ISSUE TITLE
keyboard.register_hotkey () callback function synchronization settings

### ISSUE THREAD

**Issue by motui** [boppreh/keyboard#119]
Api said reference wait () method, but the method does not elaborate. How to set up a callback method for synchronization

Windows System

**Comment by boppreh** [comment]
Wait is not used for **synchronizing** hotkeys, but for **synchronous** code. It simply means that if you write

```py
print('started')
keyboard.add_hotkey('esc, esc', lambda: print('triggered'))
print('finished')
```

then press `esc, esc`, it's always going to print "finished" *before* "triggered". If you wanted to wait for the trigger before printing "finished", you can use

```py
print('started')
keyboard.wait('esc, esc')
print('triggered')
print('finished')
```

Did you have any synchronization needs in mind?
