### ISSUE TITLE
No module named '_keyboard_event'

### ISSUE THREAD

**Issue by dagwoodland** [boppreh/keyboard#120]
On MacOS I am getting the error:
> File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keyboard/_darwinkeyboard.py", line 8, in <module>
>   from _keyboard_event import KeyboardEvent, KEY_DOWN, KEY_UP, normalize_name
> 
> builtins.ModuleNotFoundError: No module named '_keyboard_event'

Highlighting the code:
`from ._keyboard_event import KeyboardEvent, KEY_DOWN, KEY_UP, normalize_name`

**Comment by boppreh** [comment]
The line in the traceback is missing a dot (`from _keyboard_event` instead of `from ._keyboard_event`). The latest version from PyPI looks correct, and so does your code highlight. Can you check if the dot is really there?

**Comment by dagwoodland** [comment]
Yes, the dot is there.

**Comment by dagwoodland** [comment]
I have just tested my program again and it works as long as I don't run it is Wing Personal. So I think that's the problem. Thanks for your help. 😃

**Comment by glitchassassin** [comment]
Thanks for the report. I'll go ahead and close this out.
