### ISSUE TITLE
press_and_release ('home') just types a 7 in a field and 'end' types a 1

### ISSUE THREAD

**Issue by JonnyBravo887** [boppreh/keyboard#123]
I'm trying to automate some key presses in a VM on another screen. (I have a duel monitor setup.) I just cannot get the home and end keys to function as they are supposed to.  I am trying to automate filling out a form. The form has many fields, hitting the physical 'home' key on the keyboard send me to the top of the form. Hitting the physical 'end' key sends me to the bottom. Easy enough.

I am using a script to emulate this however,  trying to emulate the same thing with a python script, the text field i am currently in just writes out a 7 using this line in python:

_keyboard.press_and_release('home')_

Same with 'end'  except it writes out a '1'

_keyboard.press_and_release('end')_

The 'enter' and 'tab'  emulation works perfectly though. i.e.

_keyboard.press_and_release('tab')_ 

or 

_keyboard.press_and_release('enter')_

Any ideas?

Cheers

PS: I am on windows 10 running python 3.6

**Comment by glitchassassin** [comment]
What happens when you toggle Num Lock?

**Comment by JonnyBravo887** [comment]
yeah it worked, turned number lock off. Thanks a lot glitch!
