### ISSUE TITLE
problem with plus in write command

### ISSUE THREAD

**Issue by MrSwiss** [boppreh/keyboard#125]
When I type `keyboard.write('+') `or `keyboard.write("\053")` it will result in = instead of +.
But when I type `keyboard.write('+', exact=True)` it work as expected.
I think this is a bug, because I can't find document about this anyway.

Thanks
<img width="506" alt="capture" src="https://user-images.githubusercontent.com/3234687/36075912-b869b782-0f87-11e8-9d96-2d794adc035f.PNG">

**Comment by boppreh** [comment]
Hi @MrSwiss 

Can you please try the `suppress` branch? It contains several bugfixes and should be Shortly Available™. It seems to fix this problem in my Windows 10 machine.

**Comment by MrSwiss** [comment]
@boppreh If I use `suppress` branch, it works.
Hope it will be bug free soon.

Thank for you time.
