### ISSUE TITLE
Using keyboard on a  headless device (no keyboard attached)

### ISSUE THREAD

**Issue by nickehallgren** [boppreh/keyboard#13]
Hi and thanks for this useful library!

I've been evaluating it for a while and everything works perfectly until today when I tried it without a keyboard attached (as I will use it).

`ImportError: No keyboard files found (/dev/input/by-path/*-event-kbd).`

Must I have a keyboard attached or is there anything I can do to get around it?

**Comment by boppreh** [comment]
Right now it does require a keyboard to work on Linux, because we write the events to the device file. If there's no keyboard the OS won't have created any device files for it. 

But I agree this is a pointless limitation. The library should create a fake event device in case no hardware is found. Maybe following http://unix.stackexchange.com/a/14882/52837 if it can be done with no binaries or external libs.

**Comment by boppreh** [comment]
I think I found an alternative, but it requires X to be installed. Are you running any graphical interface, or just a headless TTY?

**Comment by nickehallgren** [comment]
Wow, you're fast :) I'm actually running X so that is no problem.

**Comment by boppreh** [comment]
Great. The alternative would require playing with drivers and um put, which is painful and would introduce potential segfaults.

I'll get back to you when I have some X code implemented to simulate keyboard and mouse events.

**Comment by boppreh** [comment]
Ok, I think it's working now. When no devices are detected on Linux it creates a fake device using the `uinput` driver (included in most kernels, and does not even require X). It worked well on my raspberry pi, allowing to simulate keyboard events through SSH.

Note this library does not have support for changing devices, unfortunately. So there must be no keyboards connected when the library call is made for it to create the uinput device. If this is troublesome for you please let me know and I'll bump the priority of this feature.

**Comment by boppreh** [comment]
The library got more popular and I'm trying to clean up the issues list. I think the problem has been solved, so I'm closing this issue. If you still need anything feel free to comment and/or reopen it, though.

**Comment by nickehallgren** [comment]
Thanks!!!
