### ISSUE TITLE
Don't work on WindowsXP

### ISSUE THREAD

**Issue by Anniywell** [boppreh/keyboard#132]
I use keyboard on XP, but it does not work.
I feel the problem is here：
```python
keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, NULL, NULL)
```
then I replace it with:
```python
keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, GetModuleHandleA(None), NULL)
```
It can work on XP，is there any problem with my changes?

**Comment by boppreh** [comment]
I don't want to get into the rabbit hole of supporting wildly out of date platforms, but if the change is as simple as that, that's OK for me. I'll first take a better look at the documentation for these functions to ensure it's not going to break anything.

**Comment by boppreh** [comment]
v0.13.0 now contains this fix. Feel free to reopen the issue if you still experience problems.

Thank you for reporting the issue and the solution at the same time!
