### ISSUE TITLE
KeePass' auto-type hotkey fails while `keyboard.wait()` is running

### ISSUE THREAD

**Issue by sharat87** [boppreh/keyboard#137]
Consider the following script (Python 3.6, Anaconda, Windows 7 64bit)

```python
import keyboard
keyboard.add_hotkey('ctrl+alt+x', print, args=['hotkey triggered'], suppress=True)
keyboard.wait()
```

While this script is running, KeePass' auto-type hotkey, (default is `Ctrl+Alt+A`) isn't working correctly. This auto-type hotkey is supposed to type out the username and password in a way similar to `keyboard.write` method's operation. For example, when it is supposed to type `sharat`, it triggeres `ctrl+s` and then types out the rest of the keys.

Note that this issue only occurs when `suppress=True`.

Additionally, in the above example, when I hit `ctrl+alt+x`, I get `hotkey triggered` printed twice. The callback is being called twice.

```bash
$ pip freeze | grep keyboard
keyboard==0.11.0
```

**Comment by sharat87** [comment]
Issue does not occur with the latest master, installed with the following command:

```shell
pip install --upgrade git+https://github.com/boppreh/keyboard.git#egg=keyboard
```

Can we get a released package soon please so I can install it directly? Let me know if I can help.

Thank you for the wonderful work.

**Comment by boppreh** [comment]
Awesome, thank you for testing master. Releasing this version is the biggest priority at the moment, I was just too busy before.

**Comment by sharat87** [comment]
No problem. Thank you.

**Comment by boppreh** [comment]
New version released to PyPI containing the fix mentioned. Thank you for your bug report, and feel free to reopen this issue or open a new one at any time you encounter new problems.
