### ISSUE TITLE
AttributeError: '_KeyboardListener' object has no attribute 'blocking_keys'

### ISSUE THREAD

**Issue by 2press** [boppreh/keyboard#139]
In the current master version I regularly encounter this exception, when calling unhook_all()

` keyboard.unhook_all()
  keyboard\__init__.py", line 534, in unhook_all
    _listener.blocking_keys.clear()
AttributeError: '_KeyboardListener' object has no attribute 'blocking_keys'`

**Comment by boppreh** [comment]
That happens when calling `unhook_all` without having ever created any hooks/hotkeys. An unusual situation, but surely shouldn't be illegal.

Should be fixed now.
