### ISSUE TITLE
TypeError: hook() got an unexpected keyword argument 'suppress'

### ISSUE THREAD

**Issue by BarocziGabor** [boppreh/keyboard#140]
I tried to use this:
    keyboard.hook(print_key, suppress=True)
however I got the exception mentioned in the title.

Checked the __init__.py on the github and it has this:
    def hook(callback, suppress=False, on_remove=lambda: None):

However in my ~/.local/lib/python3.6/site-packages/keyboard/__init__.py it looks like this:
    def hook(callback):

**Comment by LandonPowell** [comment]
I'm pretty sure the pypi version is out of date.

**Comment by boppreh** [comment]
Yes, the pypi version is very much out of date. Sorry, I'm working on it.

**Comment by boppreh** [comment]
PyPI version is now up to date. In the future I'll split the API documentation between "master" and "lastest form PyPI", but that's a future enhancement.
