### ISSUE TITLE
Not working with game emulators?

### ISSUE THREAD

**Issue by woooooopwop** [boppreh/keyboard#141]
Hey there  -

I'm new to `keyboard` and I started to do some tests with various applications (SublimeText, Steam Games such as Dirt Rally..) and everything is working as expected.

Now, I want to do the same thing with some emulators such as OpenEmu or RetroArch, and noticed my code is no longer working. I'm just using basic `keyboard.press()` for testing purposes, so I'm wondering if I should so thing differently (and why?)

I've enabled accessibility keyboards and have confirmed the inputs are detected correctly. However, I can't control my game even with the visual keyboard. 

Thanks -

**Comment by boppreh** [comment]
Hi

Sorry for not answering earlier. Did you close the issue because you fixed the problem? I very much would like to support those use cases.
