### ISSUE TITLE
[OSX] AttributeError: module 'keyboard._darwinkeyboard' has no attribute 'map_name'

### ISSUE THREAD

**Issue by peterxu30** [boppreh/keyboard#145]
I just installed keyboard on OSX 10.13.1 and I get this error whenever I try to do anything:

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keyboard/__init__.py", line 854, in write
    entries = _os_keyboard.map_name(_normalize_name(letter))
AttributeError: module 'keyboard._darwinkeyboard' has no attribute 'map_name'

This was the result of trying `keyboard.write("HELLO")`
I am running Python 3.6.5

**Comment by boppreh** [comment]
Thanks for the report. I think I fixed it, but I don't have any OSX machines to test on.

Can you try the `master` version? You can clone this repo or [download the zip.](https://github.com/boppreh/keyboard/archive/master.zip)

**Comment by peterxu30** [comment]
Thanks for the quick response! I've tried a few calls and they all work so far.

**Comment by boppreh** [comment]
Awesome, thank you for the report and the testing.

**Comment by boppreh** [comment]
The fix is now available on version 0.13.2. Please try `pip install --upgrade keyboard` to use the latest version.
