### ISSUE TITLE
Running is_pressed within a while loop

### ISSUE THREAD

**Issue by KuanHulio** [boppreh/keyboard#151]
My code looks like this:
```py
async def show_messages(guild_name: str, channel_name: str):
    code = 0
    os.system("clear")
    unformatted_text_channels = discord.utils.get(bot.guilds, name=guild_name).text_channels
    channel = discord.utils.get(unformatted_text_channels, name=channel_name.name)
    while True:
        if keyboard.is_pressed('ctrl+n'):
            code = 1
            break
        else:
            messages = await channel.history(limit=20).flatten()
            messages.reverse()
            start_message = ">>> {} ({}) ({}) ({})\n    {}"
            for message in messages:
                print(start_message.format(message.author.display_name, message.author.name, message.id, message.created_at.strftime("%Y-%m-%d %H:%M:%S"), message.clean_content))
            await asyncio.sleep(3)
            os.system("clear")
    if code == 1:
        raise ValueError
    elif code == 2:
        raise ZeroDivisionError   
 ```

And as far as I know, this seems right, however, when I run my program, it will iterate the `else` statement but when I press `ctrl+n`, it will not register. 

Am I forgetting something? (If I spam the hotkey, it will also crash and dump the core. On linux.)

**Comment by boppreh** [comment]
Hi @KuanHulio 

A shorter, self-contained script to test would be helpful in debugging the issue. Also, if the crash and core dump gave you any useful information, that would also help.

I'm not well versed in asyncio, but I think you are checking for `ctrl+n` only once every three seconds, plus the time to messages to arrive. You may have more luck using `add_hotkey('ctrl+n', do_something)`.

**Comment by KuanHulio** [comment]
Do I have to run `add_hotkey` outside of the while loop?

**Comment by boppreh** [comment]
Yes, you call `add_hotkey` only once, and it listens for hotkeys until you call `remove_hotkey` or the program exits. You can then process anything in you want inside the callback (which will be executed in a different thread), or, if you prefer to keep the asyncio pattern, raise a flag/send an event to be processed in the event loop.

**Comment by KuanHulio** [comment]
Alright thanks!

**Comment by Stinosko** [comment]
Hey, 
I see you didn't want to add support for asyncio last year. I wanna say i would love to have the support for asyncio as in python 3.7 it has become 'userfriendly-er' to use. I assume it's a lot of work but i thought i still suggest, i never know... 😄
