### ISSUE TITLE
AttributeError: module 'keyboard._darwinkeyboard' has no attribute 'map_name' on OSX

### ISSUE THREAD

**Issue by M4rkD** [boppreh/keyboard#155]
On OS X, using python3, calls to all attempted functions (write, add_hotkey, wait, record) results in an error such as the following

`>>> keyboard.write('The quick brown fox jumps over the lazy dog.')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/markdawson/anaconda3/lib/python3.6/site-packages/keyboard/__init__.py", line 854, in write
    entries = _os_keyboard.map_name(_normalize_name(letter))
AttributeError: module 'keyboard._darwinkeyboard' has no attribute 'map_name'`

**Comment by boppreh** [comment]
Hi @M4rkD 

Thansk for the report, but this is a duplicate of #145. It's fixed in master and will be in the next release.

**Comment by M4rkD** [comment]
Apologies for the duplicate. Thanks for the reply and for developing a truly useful library.

**Comment by boppreh** [comment]
No problem, it's my fault for not releasing the fix yet.

And thanks for using my library and deciding to contribute to it.

**Comment by boppreh** [comment]
The fix is now available on version 0.13.2. Please try `pip install --upgrade keyboard` to use the latest version.
