### ISSUE TITLE
LINUX Failed to create a device file

### ISSUE THREAD

**Issue by GolddolphinSKB-Fexcraftian** [boppreh/keyboard#156]
Good morning,

I'm using KUbuntu with python 3.4 (I haven't check on later versions yet) and have been unable to use they keyboard module to send events. It's worked fine for reading keypresses on my macOS system.

When I call ``keyboard.send(4)`` for the letter 'h', I get the following error:
```Python
/usr/local/lib/python3.4/dist-packages/keyboard/_nixkeyboard.py:110: UserWarning: Failed to create a device file using 'uinput' module. Sending of events may be limited or unavailable depending on plugged-in devices.
```

Any clarity on this would be grateful. I've searched for issues relating to this before, but may not have seen some.

Thanks for the help,
GoldSloth

**Comment by boppreh** [comment]
Hi GoldSloth

The Linux backend can send events in one of two ways:

- piggy-back on top of an existing keyboard device, or
- create a new fake device using uinput and send the events through this device.

The warning you see means that it failed to use uinput to create the fake device, which leaves the library limited to re-using existing keyboards. If you can't send events, it means that no existing keyboard devices were found. I don't have KUbuntu or Python 3.4 to test, but you try the following:

1. If you have a keyboard plugged in, please check if the keyboard is a registered device at `/dev/input/by-id/*-event-kbd` or `/dev/input/by-path/*-event-kbd`, or if it's listed at `/proc/bus/input/devices`.
2. If you don't have a keyboard, you'll have to enable `uinput` in your system.

Also, it would be useful if you tried `keyboard.hook(print)` or `python -m keyboard` and see if it's able to read events. If it's able to read events, but not send, it'll be much weirder.

I'm working on a different way to read and send events using xlib, but it's not in a useful state just yet.

**Comment by GolddolphinSKB-Fexcraftian** [comment]
Ahh, I missed the step of enabling ``uinput``, I'll do that and try again.

**Comment by GolddolphinSKB-Fexcraftian** [comment]
After running ``sudo python3 -m keyboard`` I get the same error.... I'm using a keyboard, and I don't have uinput enabled. There's a ``event-bkd`` device at ``/dev/input/by-id`` Which seems reasonable..

It seems I'm able to send events to it, but the numeric values given by my macOS system don't translate to the same keys pressed on my kubuntu system... 

I guess I'm going off topic with that.

**Comment by boppreh** [comment]
Ah, so you can send events, but the macOS events are incorrect? That's something else. Scan codes are only portable sometimes, so try sending the events by key name instead of scan code.

**Comment by GolddolphinSKB-Fexcraftian** [comment]
Yes, This is completely a different issue now..
With the ``keyboard._pressed_events`` I get the code ``4`` for the key ``h``, which is in the ANSI character set, but does linux use ascii instead?

**Comment by GolddolphinSKB-Fexcraftian** [comment]
Problem is there's no easy way of using python to convert between ansi and anything else... Strange.
Is there anyway to get ``keyboard._pressed_events`` to return anything else?

**Comment by boppreh** [comment]
I'm confused on what you are trying to do, so let me try to answer it from multiple perspectives:

- Yes, the keys of `_pressed_events` are scan codes, but the object is a dictionary and the values are regular `KeyboardEvent`s. If you want the name of the currently pressed keys you just have to iterate over the `keyboard._pressed_events.values()` and get `event.name` for each one.
- Avoid converting scan codes into anything else, it'll most likely break if you change hardware or OS. Especially don't take the scan code as ASCII or ANSI value.
- If you are trying to replay events from your Linux to your macOS machines, use `keyboard.hook(handler0` to get a raw stream of events, don't check `_pressed_events`.

**Comment by GolddolphinSKB-Fexcraftian** [comment]
Sorry, This is more my ignorance of the library. I'm basically taking keypresses from my macbook pro, then using a socket to send them to my iMac G5 running Kubuntu, where I intend for them to be 'pressed' there. I guess I missed that ``_pressed_events`` was a dictionary, as I was iterating through it instead. I'll close this issue now, I blame these issues down to my ignorance 😄. 
I'll let you know if I find any 'real' bugs. Thanks for your time 👍
