### ISSUE TITLE
Times for events in record()

### ISSUE THREAD

**Issue by ornariece** [boppreh/keyboard#166]
Could you add the possibility to know when the keyboard events occured during the recording ?
So maybe add smth like this :

def start_recording(recorded_events_queue=None, times_list = False):
    """
    Starts recording all keyboard events into a global variable, or the given
    queue if any. Returns the queue of events and the hooked function.
    Use `stop_recording()` or `unhook(hooked_function)` to stop.
    """
    recorded_events_queue = recorded_events_queue or _queue.Queue()

    global _recording
    
    if times_list:
        times_list = []
        def event():
            recorded_events_queue.put()
            times_list.append(time.time())
        _recording = (recorded_events_queue, times_list, hook(event))
        
    else:
        _recording = (recorded_events_queue, hook(recorded_events_queue.put))
        
return _recording

**Comment by boppreh** [comment]
I'm not sure I understand the request, since the objects in the event queue already have a `.time` attribute. For example, once you have the list of events, you can do `[e.time for e in events]` to get a corresponding "times_list".

**Comment by ornariece** [comment]
I'm sorry, i didn't get the corresponding events were objects. Thank you ! You can close the issue
