### ISSUE TITLE
Error 13 - Must be run as administrator

### ISSUE THREAD

**Issue by Unkraut3** [boppreh/keyboard#174]
Dear all,

when importing lackey I'm running into the issue described here: 
https://github.com/glitchassassin/lackey/issues/108

I'm getting the error 'Error 13 - Must be run as administrator' and cannot import lackey. According to the above link, lackey does not need to listen to key presses. Therefore, it should not be necessary to run my code as root. Unfortuntately, doing:

```
try:
   import  lackey
except:
   pass
```

does still not allow me to import lackey. Is there any way to prevent keyboard from listening to key presses? I don't want to run my application as root unless really necessary.

**Comment by glitchassassin** [comment]
Lackey does in fact listen to keypresses for a specific keyboard shortcut, `alt+shift+c`, which terminates the script. This is a Sikuli feature that Lackey implements for consistency.

However, the import should work fine, aside from displaying that error - you won't be able to use the keyboard shortcut, but as the error happens in a separate thread, the rest of the library should be unaffected.

In any case, this is not an issue with `keyboard`, and the issue you linked above was answered incorrectly. I'll add a comment to it for clarity.

**Comment by glitchassassin** [comment]
If Lackey in fact still isn't working for you, please open an issue there and I'll take a look!
