### ISSUE TITLE
Problem adding a hotkey runs associated code

### ISSUE THREAD

**Issue by jimakr** [boppreh/keyboard#176]
i have this in py file and everytime i run it when the hotkey is registered it runs the function

def csent():
     print("inside")

keyboard.add_hotkey('ctrl+q', csend)

on the other side running this from console works fine.

**Comment by boppreh** [comment]
Remove the `()` in `csend()`.

This is not a problem with `keyboard`, but simply how Python itself works. `csent` means the function itself, while `csent()` means "invoke the code from the function named 'csent', and replace this term with the returned value (None)". To add a hotkey you want just the raw function, not the result of its invocation.

**Comment by jimakr** [comment]
Actually in my code i don't have the () just misstyped here because i was from cellphone sorry for the inconvenience. Also i get an error when i try to run the hotkey later aboun nonetype and about 20 arguments i will post a log tomorrow if it helps

**Comment by boppreh** [comment]
Oh, I'm sorry, I'm used to get very beginner questions regarding function pointers. I'm reopening the issue.

**Comment by boppreh** [comment]
Also, what OS and python version are you using? Is this a full snippet that shows the error? As it is I ant reproduce the issue, and the code seems as simple as it gets for this library.

**Comment by jimakr** [comment]
ok first things first i am using windows 10 and python 3.6.5
with this simple code i have the issue look at the output in the end
`import keyboard


def copysend():
    print("inside")


print("line 8")

keyboard.add_hotkey('ctrl+q', copysend())

print("start waiting")
keyboard.wait('esc')`

and my output is after i press the hotkey:
line 8
inside
start waiting     (here i press ctrl+q)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\jim\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\jim\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\jim\PycharmProjects\pastebinclipboard\venv\lib\site-packages\keyboard\_generic.py", line 58, in process
    if self.pre_process_event(event):
  File "C:\Users\jim\PycharmProjects\pastebinclipboard\venv\lib\site-packages\keyboard\__init__.py", line 216, in pre_process_event
    callback(event)
  File "C:\Users\jim\PycharmProjects\pastebinclipboard\venv\lib\site-packages\keyboard\__init__.py", line 647, in <lambda>
    handler = lambda e: (event_type == KEY_DOWN and e.event_type == KEY_UP and e.scan_code in _logically_pressed_keys) or (event_type == e.event_type and callback())
TypeError: 'NoneType' object is not callable

**Comment by jimakr** [comment]
ok you can close the issue, i found the solution. For anyone else having this this was caused by cache settings in PyCharm (i renamed the file and it was running the old version even after i chose the new one) and it would seem that was running a cached version where the keyboard.add_hotkey('ctrl+q', copysend) was keyboard.add_hotkey('ctrl+q', copysend()) causing to run the function. after restart it was fixed and reloaded the new version. thanks a lot for your time and support it was actually a system specific error sorry for the trouble.
