### ISSUE TITLE
Reading Keypresses through SSH

### ISSUE THREAD

**Issue by ghost** [boppreh/keyboard#195]
Hello, so in my current setup, I have a desktop with a keyboard and mouse connected to that main desktop. I SSH into a Raspberry Pi that has a script that reads keyboard presses and based on the key press an action is performed. I can run the program directly on the Pi with a keyboard and mouse connected directly to it. But when I SSH into the Pi from my main desktop with the keyboard connected to the main computer, the key presses don't seem to be detected. Is there any reason why this might be happening? Is there a workaround to this? Thanks

**Comment by FadySalama** [comment]
I encountered a similar situation trying to detect ssh key-presses on a RaspPi without any connected keyboards. I confirm the behaviour.

**Comment by boppreh** [comment]
There's unfortunately no way around it, as the SSH protocol does not forward individual key events, but only characters. My suggestion is to run `keyboard` *on the computer with the keyboard connected*, and forward that to the raspberry.

You can use a simple `python -m keyboard | ssh user@raspbeery "python ./process_events.py"`, where `process_events.py` is a script that receives a stream of JSON events from stdin. This allows the process to run inside the raspberry and receive keyboard events.
