### ISSUE TITLE
add_hotkey runing the wrong callback when added on loop

### ISSUE THREAD

**Issue by cosmeoes** [boppreh/keyboard#197]
I have this code: 
```
import keyboard

dictonary = {"shift+a":"shift+a" , "ctrl+u": "ctrl+u","ctrl+q":"ctrl+q" }
for key, value in dictonary.items():
    keyboard.add_hotkey(key, lambda: keyboard.write(value),  suppress=True)

k=input("Press enter to end...")
```
So It should write "shift+a" when i press shift + a, "ctrl+u" when i press ctrl+u and  "ctrl+q" when i press ctrl+q.

But when I press any of those  any of those key combinations It writes  "ctrl+q". I think it might be because I'm setting the hotkeys in a loop or something.

Or am I doing something wrong?

**Comment by boppreh** [comment]
Yep, it's because of the loop. The usage of `value` inside the lambda is binding to a variable that lives across all loops, so it'll hold only the last value.

Try `lambda value=value: keyboard.write(value)` to rebind it.

**Comment by cosmeoes** [comment]
Oh thanks for the quick answer, that fixed it, so I assume this is a python issue isn't it?

**Comment by boppreh** [comment]
I'm glad to hear it's fixed.

Yes, it's unrelated to the library. An unfortunate feature that lots of people complain. Still, maybe a warning on one of the examples wouldn't hurt.
