### ISSUE TITLE
 import keyboard error

### ISSUE THREAD

**Issue by lunxian** [boppreh/keyboard#2]
￼ File "c:\GG-Python\WingProj\hupai\kbhit.py", line 5, in <module>
  import keyboard
File "C:\GG-Python\Anaconda\Lib\site-packages\keyboard\__init__.py", line 1, in <module>
  from .keyboard import *
File "C:\GG-Python\Anaconda\Lib\site-packages\keyboard\keyboard.py", line 8, in <module>
  import keyboard.winkeyboard as os_keyboard

ImportError: No module named winkeyboard

**Comment by boppreh** [comment]
Looking into it. For the moment you can use Python3, where the imports work as expected.

**Comment by boppreh** [comment]
The issue was already resolved by Pull Request #1 , it just wasn't uploaded to PyPi. I've uploaded version 0.6.4 with this fix. Use `sudo pip install --upgrade keyboard` to update.

Thank you for the bug report, and feel free to comment and reopen the issue if the problem persists.
