### ISSUE TITLE
Only listen inside terminal window

### ISSUE THREAD

**Issue by joveice** [boppreh/keyboard#202]
Is there a way to only listen inside the terminal window? I want etc Q to be back, but I don't want it to be activated when you are typing outside terminal.

**Comment by boppreh** [comment]
Hi @joveice 

Are you developing a Command Line Interface application? This module is meant for global hooks; if you want to get unbuffered terminal input (like one-character 'input()' without having to press 'enter'), I suggest using https://pypi.org/project/getch/ .

I'm considering adding something like this to this library (it makes sense given the name), but I'm afraid it might confuse people.

**Comment by joveice** [comment]
@boppreh I am indeed. Thanks for the suggestion.

It would be cool as I could then use custom keys, etc Q to stop and have hotkeys too. So now I have to use two libraries to have that. (I won't be using that, but just a example). I will try out that package and see if that fills my needs. Thanks!
