### ISSUE TITLE
[bugs:macosX][questions] how to send binary stream through this component to create exe, jar, zip and other files

### ISSUE THREAD

**Issue by hktalent** [boppreh/keyboard#266]
[questions]
1, browser-based vpn
2, prohibit file upload, download, prohibit using the clipboard
3, only allow keyboard input
4, how to send binary stream through this component to create bin  exe, jar, zip and other files

[questions]
1、基于浏览器的vpn
2、禁止文件上传、下载、禁止使用剪切板
3、仅允许键盘输入
4、如何通过本组件发送二进制流创建exe、jar、zip等文件

😀🤝🌹

**Comment by hktalent** [comment]
https://support.office.com/en-us/article/insert-ascii-or-unicode-latin-based-symbols-and-characters-d13f58d3-7bcb-44a7-a4d5-972ee12e50e0

encode bin file to
ALT+num

**Comment by hktalent** [comment]
When it is forbidden to paste or prohibit file uploading, upload binary files.

**Comment by hktalent** [comment]
or
1、base64 file
<img width="797" alt="image" src="https://user-images.githubusercontent.com/18223385/58460203-baf4ea80-815f-11e9-9f82-ee44a195e527.png">
```
import keyboard
import base64
import time

# pip install keyboard

f = open("/server_windows_386.exe", "rb")
data= base64.b64encode(f.read())
# print(data)
f.close()
time.sleep(5)

# keyboard.send("windows+r");
keyboard.write("cmd.exe");
keyboard.send("enter");
```
can not send?

**Comment by hktalent** [comment]
in my Mac os
<img width="555" alt="image" src="https://user-images.githubusercontent.com/18223385/58460811-ee844480-8160-11e9-89fe-90dd73b17702.png">
$ python -V
Python 2.7.16

**Comment by hktalent** [comment]
$ python3 sendFile.py
start send ...
google:tools 0x101$ python3 -V
Python 3.7.2

**Comment by hktalent** [comment]
but windows is ok

**Comment by glitchassassin** [comment]
You might try "return" instead of "enter" on OSX. I'll take another look in a couple hours when I'm in front of my Mac.

**Comment by hktalent** [comment]
@glitchassassin nothing
````
print("start send ...")
keyboard.write("whoami")
keyboard.send("return")


$ python sendFile.py
start send ...
$
```

**Comment by glitchassassin** [comment]
When I run:

```
import keyboard
print("start send ...")
keyboard.write("whoami")
keyboard.send("enter")
```

I get:

```
$ python sendFile.py 
start send ...
whoami
$ whoami
jwinsley
```

Same with either Python 2 or 3 on OSX. This is with the most recent version of keyboard from `python -m pip install keyboard`.

**Comment by hktalent** [comment]
@glitchassassin 
<img width="189" alt="image" src="https://user-images.githubusercontent.com/18223385/58486771-12637c80-8199-11e9-8035-21bab8971bcd.png">
```
$ python sendFile.py
start send ...
1$ uname -a
Darwin google.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
$
```
why?

**Comment by hktalent** [comment]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/18223385/58487005-7b4af480-8199-11e9-9584-5ccf63d1573a.png">
<img width="474" alt="image" src="https://user-images.githubusercontent.com/18223385/58487033-82720280-8199-11e9-9a2f-1d1f979c95c5.png">
 @glitchassassin 
thanks 
<img width="350" alt="image" src="https://user-images.githubusercontent.com/18223385/58487122-a9303900-8199-11e9-9252-a2ed71857c77.png">

**Comment by hktalent** [comment]
<img width="655" alt="image" src="https://user-images.githubusercontent.com/18223385/58487230-d1b83300-8199-11e9-8640-f2107e2ccf3f.png">
