### ISSUE TITLE
sdist: FileNotFoundError: 'CHANGES.md'

### ISSUE THREAD

**Issue by jayvdb** [boppreh/keyboard#269]
Installing keyboard and mouse from the sdist results in

```py
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    last_version_match = re.search('(\d+(?:\.\d+)+)', open('CHANGES.md').read())
FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES.md'
```

I suggest using PyPI `check-manifest` as part of release process to include everything sensible in the sdist, with a few exceptions configured in `setup.cfg` if required.

**Comment by w-henderson** [comment]
This should be marked as closed now.
