### ISSUE TITLE
can not receive keyboard input key when input in pc administrator dialog

### ISSUE THREAD

**Issue by 18437931018** [boppreh/keyboard#284]
when i input passsword  in pc administrator dialog I can`t receive the keyboard input anyway!!

![QQ截图20190903111756](https://user-images.githubusercontent.com/24566821/64141957-a4d08780-ce3c-11e9-9a61-6ddcfe5f217b.png)

**Comment by 18437931018** [comment]
Who can tell me why

**Comment by boppreh** [comment]
Windows security feature. Sensitive windows like UAC prompt cannot have their events manipulated. And a reminder that intercepting passwords without consent is illegal.
