### ISSUE TITLE
Need help to configure

### ISSUE THREAD

**Issue by csarcom** [boppreh/keyboard#29]
Iam trying to set .press() setup, without lucky.

I want something like that, when I prest alt+g then holds down F8 key until I press 'esc'

Is that possible?

**Comment by boppreh** [comment]
Sounds like a combination of `add_hotkey` and using the callback invoke `press`, `wait` and `release`. What have you tried, what happened and what did you expect?

**Comment by boppreh** [comment]
Hi csarcom

Sorry but I'll close this issue due to lack of feedback on the problem. If you are still having trouble, please don't hesitate to comment here and reopen the issue.
