### ISSUE TITLE
segmentation fault: 11

### ISSUE THREAD

**Issue by YiMeChen** [boppreh/keyboard#323]
When trying to record or add hotkey, python returns "Segmentation fault: 11".

macOS catalina 10.15.3
python 3.7.5

The same code worked before, the only change i can think of is the macOS update that might caused this. Does anyone have the same issue?

Thanks.

**Comment by mariana0pachon** [comment]
I am also trying to run any of the given examples using Python 3.7.6 on macOS Mojave 10.14.6 and I keep getting 'segmentation fault'. I tried installing the latest version from the Git repository and I still get the same error.

**Comment by roboticsware** [comment]
Same as here. How did you fix it? Thanks.
