### ISSUE TITLE
Linux problems on basic example

### ISSUE THREAD

**Issue by fpp-gh** [boppreh/keyboard#34]
Hi, me again :-)
Got me a Linux laptop and trying to really use the lib on it, because of course, no AutoHotKey...
Unfortunately I can't get it to run a two-line test example (import keyboard, define one abbreviation).
With Python 2.7 it bombs:
```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/fpp/python/PyHotKey/keyboard/__init__.py", line 114, in listen
    _os_keyboard.listen(self.queue)
  File "/home/fpp/python/PyHotKey/keyboard/_nixkeyboard.py", line 111, in listen
    build_device()
  File "/home/fpp/python/PyHotKey/keyboard/_nixkeyboard.py", line 106, in build_device
    device = aggregate_devices('kbd')
  File "/home/fpp/python/PyHotKey/keyboard/_nixcommon.py", line 145, in aggregate_devices
    uinput = make_uinput()
  File "/home/fpp/python/PyHotKey/keyboard/_nixcommon.py", line 48, in make_uinput
    uinput.read = lambda n: Queue().get()
AttributeError: 'file' object attribute 'read' is read-only
```
With Python3.5 there is no exception but no abbreviation expanding either...

This is on XUbuntu 16.04, running the script as root in xterm and testing in Mousepad.
Anything I'm doing wrong ?...

**Comment by boppreh** [comment]
Looks like two different bugs, one relating to an attribute not bei g writable on Python2, and the other caused the Python3 code to fail. The first should be easy to fix, I'll take a look as soon as I get home today. The other may require more detective work, so any further information is welcome. 

Thank you for the report.

**Comment by fpp-gh** [comment]
You're right, I hadn't dug into the second one deep enough, I think I see where it's coming from.
Probably 2.7 will act the same when its own bug is fixed, and I'm not sure you can do anything about it.

When my simple two-liner test didn't work, I decided that I needed a larger sample of abbrevs just to be sure. So I tried one of my lists from a few months back, and found something surprising:
out of a dozen, exactly ONE was working.
So the script was not entirely stalled, and also the `wait('shift-X')` at the end was working.
After puzzling around for a while, I realized that the keyword for that working abbrev was probably the only one made of characters from the QWERTY layout (i.e. not a, z, m, w, x, numbers etc.).
So I remapped all the other keywords to simple double chars (avoiding those), and sure enough, they mostly could be made to expand... but interpreted in QWERTY.
So it's another layout problem again, a probably a hairy one.
In this special case we have a Chromebook, with the specific keyboard layout imposed by Google.
It runs on GalliumOS, a (quite nice) variant of XUbuntu 16.04 tuned to run specifically on Chromebooks.
Amongst other things it comes with a generous dose of keyboard overlays to make its use more PC-like.
I don't know how it works exactly (probably several layers & tools involved), but there's a fair chance that it's playing havoc with your code here.
https://wiki.galliumos.org/Media_keys_and_default_keybindings

**Comment by boppreh** [comment]
The Linux + Python2.7 error is fixed (turns out that line was unnecessary). Rookie mistake, I'm sorry.

Unfortunately the second problem is trickier. There is nothing QWERTY in this library (zero hardcoded keys), so the bias must be coming from somewhere else.

Try the following:

    sudo python -m keyboard

Press some layout specific keys, and note down the scan_code reported, say `44`. Then

    sudo dumpkeys --keys-only | grep -E "^keycode +44"

Which should print something like this:

    keycode 44 = +z

Which shows that "z" is mapped to scan code 44. This should match the event name printed by the previous `python -m keyboard`.

**Comment by fpp-gh** [comment]
I have never doubted that the lib was keyboard-agnostic, and I'm quite sure that whatever is wrong here comes from the system setup and is way over my head :-)
I have gathered two files with the results from the above commands for the entire Chromebook keyboard in AZERTY layout.
Will write some code tomorrow to merge them and report on that. Thanks for the tips !

**Comment by fpp-gh** [comment]
Okay, here is the compiled result from the two tests, for the four character rows (minus the special keys):
```
 Scan_code    Name    Output  keycode_name 
------------------------------------------ 
     1        esc       ^[        Escape    
     41        `        @         grave     
     2         1        &          one      
     3         2        é          two      
     4         3        "         three     
     5         4        '          four     
     6         5        (          five     
     7         6        -          six      
     8         7        è         seven     
     9         8        _         eight     
     10        9        ç         nine     
     11        0        à         zero     
     12        -        )         minus     
     13        =        =         equal     
     16        q        a           +q      
     17        w        z           +w      
     18        e        e           +e      
     19        r        r           +r      
     20        t        t           +t      
     21        y        y           +y      
     22        u        u           +u      
     23        i        i           +i      
     24        o        o           +o      
     25        p        p           +p      
     26        [       None    bracketleft  
     27        ]       None    bracketright 
     30        a        q           +a      
     31        s        s           +s      
     32        d        d           +d      
     33        f        f           +f      
     34        g        g           +g      
     35        h        h           +h      
     36        j        j           +j      
     37        k        k           +k      
     38        l        l           +l      
     39        ;        m       semicolon   
     40        '        ù      apostrophe  
     43        \        *       backslash   
     86        <        <          less     
     44        z        w           +z      
     45        x        x           +x      
     46        c        c           +c      
     47        v        v           +v      
     48        b        b           +b      
     49        n        n           +n      
     50        m        ,           +m      
     51        ,        .         comma     
     52        .        :         period    
     53        /        !         slash     
------------------------------------------ 
```
First two cols are from `keyboard` output when pressing keys, third is what's printed in the xterm
The last id the dumpkeys name for the scan code.
So, as far as I understand it, the situation is this:
* what `keyboard` gets from the system hooks is a plain-vanilla QWERTY layout
* the (mostly) AZERTY layout I experience as a user, in console or X, comes from additional black magic in layers above

A quick 'n dirty fix is to simply cheat in the abbreviation definitions by using the hidden layout for both triggers and expansions. I tried it, it works, although it does hurt readability :-)
The proper, hardcore fix would be to replace all that stuff with my own remapping, but I know from experience that it's above my patience threshold :-)
Probably I'll end up with a script that reads a list of abbrevs in the right format, and transposes them to QWERTY before adding them, making them seem to "work as expected" :-)

**Comment by boppreh** [comment]
Unfortunately I don't see a way to adapt the library to your needs.

My suggestion is to hardcode the mapping `scan_code -> name` yourself, and deal only in scan codes. If you need a shifted character, press and hold shift by using its scan code.

The existing code for abbreviations will probably be unable to help you when using scan codes, but you can simply copy, paste and adapt. All in all it's less than 30 lines of code. If you think any of this would be helpful to other users, I would be glad to adapt into the library.

And thank you for the in-depth reports.

**Comment by fpp-gh** [comment]
Somehow I expected/feared you would say this :-)
I don't think I understand enough at the system level to head down that way... I'm just a user :-)
But I believe several people have already done this, or something very similar.

All this reminded me that a few years back, when I was (already) using Linux on a Chromebook (by way of the nifty 'Crouton' chroot framework), I did search for Linux alternatives to AutoHotKey.
The landscape was quite bleak, with only a couple of working but stalled solutions : IronAHK, a straight port of AHK in C#/.Net (eeek), and AutoKey, an independent concept with similar goals.
Autokey did work though, and I used it for a while. So I thought I'd revisit the landscape for changes.

It's still bleak (the original Google code repo for Autokey has disappeared), except that some brave gentleman has ported and enhanced Autokey to python3 and maintains it on Github (still fixing bugs):
https://github.com/autokey-py3/autokey-py3
I tried it this morning and it still works, so it must operate at an entirely different level than `keyboard`.
Maybe it could inspire you if you haven't looked at it already ?

As for me, my main issue with Autokey is that it's very UI-centric: defining an abbreviation requires several dialogs and (at least) two files on disk.
AutoHotKey has a cryptic but efficient syntax to define an abbreviation in one line, with everything in one file.
The logic is very similar though, so it should be easy enough to script a conversion between the two, or even a simplified UI just for abbrevs (Autokey can do much more of course).

**Comment by boppreh** [comment]
Autokey-Py3 seems to select between two interfaces: an EventDevice one (like `keyboard`) and an XLib one (via `python-xlib`). Maybe it's the X part that is behaving correctly.

Another user suggested using XLib by default (maybe using ctypes to avoid the dependency), and falling back to EventDevice only if X is unavailable. This would also remove the requirement of having root access. I'm still working on it, but there's a chance this problem will fix itself once `keyboard` starts using X.

**Comment by fpp-gh** [comment]
Indeed that would be excellent news !
I will make do and be thankful for AutoKey in the meantime, but boy is that UI clunky...

I wrote a small script to turn my 40+ AHK abbreviations (one per line in a single INI file) into twice as many TXT and JSON files which I copied to the Chromebook.
AK is supposed to watch its data folder and load the new files just by closing/reopening its UI from the task bar icon, but that only got me a half-dozen... actually I had to shut it down completely and restart it to get the rest :-)
And it's also quite slow to pick up option changes to existing entries done through the UI...

I'll be glad to beta-test the X version of `keyboard` when it's done ! :-)

BTW, I'm not sure it's worth the trouble using ctypes to avoid the XLib dependency... it's not a huge lib (about 1MB with the .pyc caches) and it seems to work well.

**Comment by fpp-gh** [comment]
New year incentive post... or not :-)

Thought I'd mention that I have a new workstation in the office : this one is *much* saner that the other one, and it runs Linux... but of course I have no root/sudo...

So more than ever I'm looking forward to test the XLib version of `keyboard` :-)

**Comment by boppreh** [comment]
Hi, I'm still here. Free time is shorter than ever, but I'm doing what I can.

That sounds awesome. Please come back to tell me all the gory details on how it failed. I hope to eventually have something near-bullet-proof, since this kind of tool requires a lot of trust from the user.

**Comment by fpp-gh** [comment]
Re: free time -- don't we all :-)

Does your second sentence mean that there is already some XLib support in the current branch ?
I sort of missed that...

**Comment by boppreh** [comment]
Oh, sorry, I misread your comment. No, only file devices now. Though with xoviat's pull request I'll have to add XLib support to keep the feature parity.

Though the mouse part uses XLib for absolute positioning.

**Comment by fpp-gh** [comment]
OK, no sweat. Just whistle when it's time :-)

**Comment by boppreh** [comment]
Meanwhile, do you mind if I close this issue? I don't like having an open issue named "Linux problems on basic example". I know it's still giving you problems, but until we dig deeper or find some other system where the reproducible, there's not much I can do.

**Comment by fpp-gh** [comment]
Yup, done !
