### ISSUE TITLE
Not reading events from  specific app.

### ISSUE THREAD

**Issue by ppel123** [boppreh/keyboard#348]
I am writing an app based on this module and noticed that when I was writing in the Texmaker (for latex) the keyboard module does not read the keys pressed.
What could be the problem here?
Did someone faced that again?

**Comment by libbkmz** [comment]
I've found that TaskManager in Win 10 is also capturing all events. Keyboard and mouse python modules are silent while interacting with Task Manager. Are there any workarounds for that?

**Comment by ppel123** [comment]
Personally Ι haven't found something yet.

**Comment by libbkmz** [comment]
When I run my python script on Windows with Admin privileges, everything becomes normal. You should try it too. Maybe it can help

**Comment by ppel123** [comment]
Does the same solution work, if Ι have created an executable (based on keyboard module)?
