### ISSUE TITLE
Scan codes not set

### ISSUE THREAD

**Issue by glitchassassin** [boppreh/keyboard#35]
Certain applications with low-level functionality (like Citrix) check the scan code for keyboard events as well as the virtual key code. If the scan code isn't set, they will miss certain keys like the arrow keys (though other keys will work fine).

I'm running into this issue with the current release of `keyboard`. I'll submit a pull request in a bit.

**Comment by boppreh** [comment]
Thanks. Just note that some keys have no scan code (e.g. media keys).

**Comment by glitchassassin** [comment]
In that case the scan code will be set to zero, which is the default currently.

**Comment by glitchassassin** [comment]
I tried rewriting this to use SendInput instead of the older keybd_event, but for some reason it wasn't working so I just modified keybd_event to include the scan code. It seems to be working now in my tests.

**Comment by boppreh** [comment]
Did it fix your Citrix issue?

**Comment by glitchassassin** [comment]
Yep!

**Comment by boppreh** [comment]
@glitchassassin if you don't mind, I'm closing the issue. If you still experience problems please don't hesitate to reopen. And thanks again for the pull request.
