### ISSUE TITLE
Mac OSX [ModuleNotFoundError]

### ISSUE THREAD

**Issue by Xandino** [boppreh/keyboard#363]
Hello,
I am simply trying to implement this package but I cannot get it to import. I was testing the fresh install in the python IDE interactive shell and encountered this.

`import keyboard
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'`

I installed the package using `pip3 install keyboard` and found an old thread with this problem, the solution was upgrading the module to the newest version using `pip3 install --upgrade keyboard`; both command executed fine

I am currently using Keyboard 0.13.5
with Python 3.7.4
on MacOS Catalina 10.15.4

Feel free to ask for information not provided if needed.

**Comment by DemoMoon** [comment]
Hi，How to solve it？please

**Comment by DemoMoon** [comment]
(venv) demodeMacBook-Pro:deploy_demo demo$ python
Python 3.7.5 (default, Nov 1 2019, 02:16:32)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

import keyboard
Traceback (most recent call last):
File "", line 1, in
ModuleNotFoundError: No module named 'keyboard'
exit()
(venv) demodeMacBook-Pro:deploy_demo demo$ pip show keyboard
Name: keyboard
Version: 0.13.5
Summary: Hook and simulate keyboard events on Windows and Linux
Home-page: https://github.com/boppreh/keyboard
Author: BoppreH
Author-email: boppreh@gmail.com
License: MIT
Location: /Users/demo/PaddlePaddle/DeepSpeech-release-v1.8.5/tools/venv/lib/python3.7/site-packages
Requires: pyobjc
Required-by:
(venv) demodeMacBook-Pro:deploy_demo demo$

**Comment by DemoMoon** [comment]
@ Xandino
