### ISSUE TITLE
Not all keys are getting recognize

### ISSUE THREAD

**Issue by luis0810** [boppreh/keyboard#37]
I'm using the keyboard.hook function and certain keys like "ñ", "ç", "´", " ' ", "¡" and "º" are not getting recognize. Also when you input something like shift+. it recognizes something like left shift and . instead of : . Is there a way to change that? 
Great job on the code btw, pyhook is a mess.

**Comment by boppreh** [comment]
Hi. Thanks for the compliment.

What OS and Python version are you using? The OS is especially important, because the backends are completely different.

**Comment by luis0810** [comment]
Windows 7 and python 3.5.2, all 32 bits.

**Comment by boppreh** [comment]
There as a tiny but important mistake on the Windows backend that prevented many keys from receiving their correct names.

Could you please try the latest version from the master branch?

**Comment by luis0810** [comment]
Didn't work, also the result from run_test.sh if that helps
![test](https://cloud.githubusercontent.com/assets/19367246/21294754/8feac6a4-c512-11e6-9536-18979c081614.PNG)

**Comment by boppreh** [comment]
What happens exactly? Is the code never triggered? An error? Also, can you post an example of the code that is giving you trouble?

Also, unfortunately there are tests only for the "frontend" (high abstraction level), so they won't catch the issue. I didn't want the tests to be clicking around on the users computers, and it's hard to have determinism when keyboard layouts differ so much. I'm open to suggestions.

**Comment by luis0810** [comment]
```
import keyboard, pythoncom
data=""
def keypressed(callback):
	global data
	data+=callback.name
	print(data)
obj = keyboard.hook(keypressed)
pythoncom.PumpMessages()

```

Just detecting keys, when i press those problematic keys nothing happens, not a space or anything just as i have not pressed any keys.

**Comment by boppreh** [comment]
Ok, found another error. It was an issue when processing keys that didn't have Virtual Key Codes.

I have no idea how this was not caught sooner, sorry. Please try the newest master branch, please.

**Comment by luis0810** [comment]
Yeah that worked almost perfectly, just one key has problems now.
Once `´` is pressed I get this error and all the following keys stop working and give the same error.
![asde](https://cloud.githubusercontent.com/assets/19367246/21295081/29a1952c-c51b-11e6-985d-fde541b770d9.PNG)

**Comment by boppreh** [comment]
Oh good. Thanks for your patience.

This new problem is unrelated to the library, and happens because the windows console is not using UTF-8 encoding.  When trying to print a character outside the available range, Python throws an error. The culprit is the `print(data)` data. You can either change the console encoding, or re-encode the string before printing it.

For testing, you can print just the bytes and see that they are there.

**Comment by luis0810** [comment]
Oh right, it's fine then, thanks for the quick response.

**Comment by boppreh** [comment]
@luis0810 if you don't mind, I'm closing the issue. If you still experience problems please don't hesitate to reopen.
