### ISSUE TITLE
🦶 When activate suppress, first key doesn't work

### ISSUE THREAD

**Issue by yedhrab** [boppreh/keyboard#373]
If I run this code, I can't use <kbd>window</kbd> (`win`), key is there any option to suppress just<kbd>window</kbd> + <kbd>r</kbd> (`win+r`)

```py
import keyboard

def some_func():
    print("hello")

keyboard.add_hotkey("win+r", some_func, suppress=True, trigger_on_release=True)
```

**Comment by GrayStrider** [comment]
I recommend you to use autohotkey to suppress keys instead. For some reason today suppress=True stopped working altogether for me.

**Comment by yedhrab** [comment]
Thank you for your explaining

**Comment by fregapple** [comment]
Hey I have notice the same thing, did you workout a resolution? or Go with a different library?

**Comment by yedhrab** [comment]
I used autohotkey. But today, I'm using mac and dont interest about it any more
