### ISSUE TITLE
How to clear input buffer after pressing hotkey for wait()?

### ISSUE THREAD

**Issue by codenotworking** [boppreh/keyboard#375]
My code on Windows:
```python
import msvcrt
import keyboard

def pressed_key(e):
    if e.event_type == keyboard.KEY_DOWN:
        while msvcrt.kbhit():
            msvcrt.getch()

print("Press [p] to proceed: ")
keyboard.hook(pressed_key)
keyboard.wait("p")
```
When I run this script in Windows Terminal, PowerShell 5.1, or Command Prompt, the hotkey ("p") from wait() is echoed to the console:
```
Press [p] to proceed:
PS C:\> p
```
Is there anyway to prevent this?

**Comment by glitchassassin** [comment]
Have you tried adding the `suppress` parameter to your `wait` call?

```
keyboard.wait("p", True)
```

https://github.com/boppreh/keyboard#keyboardwaithotkeynone-suppressfalse-trigger_on_releasefalse

**Comment by codenotworking** [comment]
Well look at that.  It worked.  I didn't know what "suppress" was for.  Thanks.
