### ISSUE TITLE
keyboard.send not working for one after one operation

### ISSUE THREAD

**Issue by donno2048** [boppreh/keyboard#380]
When I try to run:
```python
import keyboard
keyboard.send('alt+tab')
keyboard.send('alt+F4')
```
it's just switching the window, but when I use:
```python
import keyboard
import time
keyboard.send('alt+tab')
time.sleep(0.1)
keyboard.send('alt+F4')
```
it's working, is it possible to create a sleep function for exact time?

**Comment by XxSamixX123** [comment]
Hi. Is this issue still relevant? I found a way to fix your problem

**Comment by donno2048** [comment]
Yes...
I'm using the second one with **almost** no problem...

**Comment by XxSamixX123** [comment]
Okay, good to know.
As I understand, you need the code to sleep, untill the computer switches the window. Correct me if I'm wrong.
The solution I found is to import the following:

from win32gui import GetWindowText, GetForegroundWindow

Then what you can do is check before pressing 'alt+tab', which window you are on. Something like:
window = GetWindowText(GetForegroundWindow())
And after sending the 'alt+tab' use freeze the code (like the sleep function) with something like:

while True:
     if window != GetWindowText(GetForegroundWindow()):
             break


Hope this helps.

**Comment by donno2048** [comment]
Thanks, pretty simple and elegant...

**Comment by donno2048** [comment]
What am I missing?

I'm using this piece of code:

```python
import keyboard
from win32gui import GetWindowText, GetForegroundWindow
window = GetWindowText(GetForegroundWindow())
keyboard.send('alt+tab')
while window == GetWindowText(GetForegroundWindow()):pass
keyboard.send('alt+F4')
``` 
which switches windows without closing it...

**Comment by donno2048** [comment]
I found the reason, there is a state named: Task Switching

I will use:
```python
while GetWindowText(GetForegroundWindow()) in [window,"Task Switching"]:pass
```

**Comment by XxSamixX123** [comment]
Oh Okay, didn't see that state.
I'm glad you found a way to fix it.

**Comment by donno2048** [comment]
when I used the code:
```python
import keyboard
from win32gui import GetWindowText, GetForegroundWindow
window = GetWindowText(GetForegroundWindow())
print(window)
keyboard.send('alt+tab')
while GetWindowText(GetForegroundWindow()) in [window,"Task Switching"]:print(GetWindowText(GetForegroundWindow()))
keyboard.send('alt+F4')
```
as some kind of self debugging the output was literally nothing (not Python or Task Switching) so I added another state "" and now it's working...

final code:
```python
import keyboard
from win32gui import GetWindowText, GetForegroundWindow
window = GetWindowText(GetForegroundWindow())
print(window)
keyboard.send('alt+tab')
while GetWindowText(GetForegroundWindow()) in [window,"Task Switching",""]:pass
keyboard.send('alt+F4')
```
