### ISSUE TITLE
Can't map some keys

### ISSUE THREAD

**Issue by bpinto** [boppreh/keyboard#40]
Hi, thanks for this library, I'm trying to make use of it to create a simple custom hotkey "alias". I'm on a MacBook Air running Linux (Gentoo).

```
import keyboard
import time

keyboard.clear_all_hotkeys()

keyboard.add_hotkey('win+c', lambda: keyboard.send('ctrl+c'))
keyboard.add_hotkey('win+v', lambda: keyboard.send('ctrl+v'))

keyboard.add_hotkey('win+l', lambda: keyboard.send('ctrl+l'))
keyboard.add_hotkey('win+e', lambda: keyboard.send('ctrl+l'))

while True:
    time.sleep(10)
```

On the script above, `win+l` and `win+e` are calling the same keyboard hotkey but only `win+e` works. I'm hitting those hotkeys on Chrome browser.

If I change those mappings to a debugger output:

```
keyboard.add_hotkey('win+c', lambda: print('ctrl+c'))
keyboard.add_hotkey('win+v', lambda: print('ctrl+v'))

keyboard.add_hotkey('win+l', lambda: print('ctrl+l'))
keyboard.add_hotkey('win+e', lambda: print('ctrl+l'))
```

I do see the output on the console. Do you have any idea what could be cause these events to not be correctly processed by chrome?

P.S.: I don't think it's relative to Chrome, as the same hotkeys don't work on other applications (e.g. termite).

**Comment by glitchassassin** [comment]
Is Win+L already set up somewhere as a hotkey?

Does it work if you run it with `sudo`?

**Comment by bpinto** [comment]
@glitchassassin 
I'm running this with `sudo` already :+1: .

I don't think those hotkeys are mapped, I haven't at least. I tried these shortcuts on different applications and they are not triggered as well. As it's not common for linux environments to map `win/mod4` keys I don't think these hotkeys were mapped by something else.

P.S.: I'm running a very trim version of gentoo with i3.

**Comment by boppreh** [comment]
> P.S.: I'm running a very trim version of gentoo with i3.

Are you using the win as mod key?

Also

Did `win+c` to `ctrl+c` work? Otherwise the problem could stem from "reusing" the same key (`c`) on both sides.

**Comment by bpinto** [comment]
@boppreh I'm trying to use `win` key as `mod`, yes, can I use `mod` instead?

These are the i3 mappings if useful for nomenclature on linux:
```
set $alt Mod1
set $cmd Mod4
set $ctrl Control
```

`win+c` to `ctrl+c` didn't work either. I hadn't thought about the possibility of the problem being on reusing the key, but I'm going to try it now.

**Comment by boppreh** [comment]
By mod key I meant the i3 mod key, but doesn't look like it.

Also notice that hotkeys are triggered on key press, so the keyboard.send happens while you are still holding down the keys. Maybe try adding a sleep before the send, as a test?

**Comment by bpinto** [comment]
@boppreh 

I just changed the keys so that they are not reuse and at least for some hotkeys it worked (not for all).

I tried some sleep yesterday and couldn't get much done, it wouldn't be too reliable either. Is there a way to trigger it on release?

Another question, whenever I hit `win+c`, the hotkey is called but the letter `c` is also printed, is there a way to stop this? I think it's a similar function to `stopPropagation()` from javascript.

**Comment by boppreh** [comment]
> I tried some sleep yesterday and couldn't get much done, it wouldn't be too reliable either. Is there a way to trigger it on release?

No, there's no support for release triggers. There hasn't been much need yet, and you can always just process events individually, which is what `add_hotkey` does behind the curtains. For example:

```
def process(event):
    if event.event_type == 'down': return
    if (event.name == 'c' and keyboard.is_pressed('win')) or (event.name == 'win' and keyboard.is_pressed('c')):
        print('triggered')
keyboard.hook(process)
```

> Another question, whenever I hit win+c, the hotkey is called but the letter c is also printed, is there a way to stop this? I think it's a similar function to stopPropagation() from javascript.

Yes, but in Windows only at the moment. I just merged a pull request from @xoviat that deals with this. For Linux suppressing keys requires cooperating from X, which the library avoids at the moment. But this is an important feature that is on the roadmap.

> P.S.: Sorry for a newbie Python question, but what would be the correct syntax for setting the delay here?

You almost got it, just pass the `1 second` to the inner call instead:

    keyboard.add_hotkey('win+c', lambda: keyboard.call_later(keyboard.send, ['ctrl+a'], 1))

**Comment by bpinto** [comment]
I have just tried the sleep and it worked. I'll try to implement something here to handle this without the sleep.

Thanks!

**Comment by bpinto** [comment]
@boppreh 

I have worked on it trying to make it look similar to `add_hotkey`, let me know if there is something wrong you notice or something I could improve:

```
def add_on_release_hotkey(hotkey, callback, args=(), suppress=False, timeout=1):
    # How could we reuse keyboard.all_modifiers?
    all_modifiers = ('alt', 'alt gr', 'ctrl', 'shift', 'windows')

    steps = keyboard.canonicalize(hotkey)

    state = keyboard._State()
    state.step = 0
    state.time = keyboard._time.time()

    def handler(event):
        if event.event_type == 'down': return
        if event.event_type == keyboard.KEY_DOWN:
            return

        timed_out = state.step > 0 and timeout and event.time - state.time > timeout
        unexpected = not any(keyboard.matches(event, part) for part in steps[state.step])

        if unexpected or timed_out:
            if state.step > 0:
                state.step = 0
                # Could be start of hotkey again.
                handler(event)
            else:
                state.step = 0
        else:
            state.time = event.time

            modifiers = [part for part in steps[state.step] if part in all_modifiers]
            non_modifiers = [part for part in steps[state.step] if part not in all_modifiers]

            if (all(keyboard.is_pressed(part) for part in modifiers) and keyboard.matches(event, non_modifiers[0])):
                state.step += 1
                if state.step == len(steps):
                    state.step = 0
                    callback(*args)
                    return suppress

#    keyboard._hotkeys[hotkey] = handler
    if suppress:
        keyboard._suppress_hotkey(steps, timeout)
        keyboard._hotkeys_suppressed[hotkey] = timeout

    return keyboard.hook(handler)

add_on_release_hotkey('win+c', lambda: keyboard.call_later(keyboard.send, ['ctrl+c']))
add_on_release_hotkey('win+v', lambda: keyboard.call_later(keyboard.send, ['ctrl+v']))
```

It works on the terminal but it doesn't work on Chrome for instance, I think it's the lack of suppress that is causing this, but can't confirm because I'm not on windows. :(

**Comment by bpinto** [comment]
@boppreh sorry to ping you but do you see anything wrong with the snippet above? Or do you think it's the lack of supress on Linux that is causing this?

**Comment by boppreh** [comment]
Sorry, I missed the notification of your last message. I don't have time to look at it right now, but I know the hotkey code is tricky, I wouldn't be surprised if it's not working because key up events violate some subtle assumption.

Ill take a look as soon as I am.

**Comment by boppreh** [comment]
Your code was not working because of the `keyboard.is_pressed(part)` part when checking if the hotkey has been completed. When the handler is called, the key has already been registered as released and therefore the check fails.

The fix was indeed tricky, but I implemented on the master branch as a `trigger_on_release` flag. Please let me know if you find any problems with it.

**Comment by bpinto** [comment]
@boppreh that's awesome! Thank you!

I have just checked and it's working here, there is only one small detail which is if I press the combination too quickly, it is as if I didn't press it. So I need to to hold `cmd`, press `v` and release `v` in order to get that right. If I for instance release both `cmd` and `v` at the same time which is what we usually do, it does not recognize it.

**Comment by boppreh** [comment]
Hmm, the suppress code is even trickier than the hotkey code, and was introduced by a pull request. I'll have to take some time to check it, but it may take some days.
