### ISSUE TITLE
Super/meta key on Linux

### ISSUE THREAD

**Issue by iiPythonx** [boppreh/keyboard#401]
100% duplicate of #222 , although this seriously needs answered.

So, I'm trying to make a screenshot-like utility using this script which is going to use the windows snip n' sketch shortcut (Super+Shift+S), however I can't figure out how to get this to work on Linux. It just doesn't do anything.

Any ideas of what to do?

**Comment by gavinkrezel** [comment]
If I understand you correctly, you kind of answered your own question. The **_Windows_** snip n' sketch tool is a tool for **_Windows_**.

Now, considering you are on this forum in the first place, I figure you probably already knew that, so if that is the case, could you clarify what you are asking?

**Comment by gavinkrezel** [comment]
So if I interpret your question another way, you are just asking about the super key not working. I don't have time to look into it right now, but at some point I will probably dig back into the source code and figure out why.

Good luck!

**Comment by ii-Python** [comment]
To clarify, I'm asking exactly **how** does somebody map to the menu/super key in the first place? I've tried `Super`, `S` (which i assume means shift), `M`, `Meta`, etc.

**Comment by GammaGames** [comment]
I'm able to get super with `scan_code=125`, is that expected? The `name` is reported as `"alt"`

**Comment by sebastiansam55** [comment]
Commenting to add that it would be nice if there was a translation back into scan codes. There is `key_to_scan_codes` but not the other way around afaik.

But if you're writing something on linux you can see the scan codes with `evtest`. 

I use `evdev` for some hotkey/mapping stuff but that is way too low level for a screen shot app.

**Comment by iiPythonx** [comment]
Gonna close this since I haven't used this library in ages (and forget I opened this).
