### ISSUE TITLE
UAC?

### ISSUE THREAD

**Issue by YiMeChen** [boppreh/keyboard#425]
Hi guys,

I have been using this library for some time, and it has work out great and as expected. 
I run across a workflow that would require going through uac, but it doesn't seem like this library work for this purpose, the function seems to be running as expected but not registering events at uac. It is ran as admin.

Can anyone confirm? Perhaps im missing something or if anyone can give me a lead on such.

Thanks!

**Comment by boppreh** [comment]
That's correct. For security reasons Windows does not allow normal programs to see, block, or inject commands into UAC prompts.

You could maybe start the application on an elevated context, so that there's only one UAC popup at the start and none during execution?

**Comment by YiMeChen** [comment]
Got it. Thanks!
