### ISSUE TITLE
Source package doesn't include "CHANGES.md"

### ISSUE THREAD

**Issue by dartg** [boppreh/keyboard#43]
The source ZIP in PyPI doesn't include the file CHANGES.md, which makes `setup.py` fail in the following line:

`last_version = re.search('(\d+(?:\.\d+)+)', open('CHANGES.md').read()).group(1)`

**Comment by boppreh** [comment]
I couldn't reproduce the issue, but now the CHANGES and README files are being explicitly added to the manifest. Please tell me if the version v0.9.10 fixes the problem for you.
