### ISSUE TITLE
"Clear" AttributeError

### ISSUE THREAD

**Issue by glitchassassin** [boppreh/keyboard#45]
When I try to define a hotkey "alt+shift+c", I get the following message:

    ('Error in keyboard hook: ', AttributeError("'list' object has no attribute 'clear'",))

I'm not immediately sure where this error is originating from, but it looks like the `_keys_suppressed` list in the `KeyTable` object in `_suppress.py` doesn't have a `clear()` method (perhaps it should be a `set` instead of a `list`?)

**Comment by boppreh** [comment]
Clear is a method implemented in Python 3. This is not the first time this method has bitten me in this project. I'll add a grep for this string in the tests. 

It should be fixed as soon as I get home.

**Comment by boppreh** [comment]
Fixed in 9228f63 , thanks for the report. As always, feel free to reopen the issue or contact me if anything funny happens.
