### ISSUE TITLE
is there any way to not miss any key press?

### ISSUE THREAD

**Issue by isaksc2** [boppreh/keyboard#451]
I want to print every letter that I type, but if I type "a" followed by "b", b will not get printed if I press "b" before releasing "a". So if you type fast you will miss half of the letters usually, can I fix this?

Here's my current implementation

```
import keyboard
import string
from threading import *


keys = list(string.ascii_lowercase)

def listen(key):
    while True:
        keyboard.wait()
        print("[+] Pressed",key)

threads = [Thread(target=listen, kwargs={"key":key}) for key in keys]
for thread in threads:
    thread.start()
```

thanks!

**Comment by FabianSt305** [comment]
1.
Why doesn't this block instantly? keyboard.wait() doesn't stop. You mean keyboard.wait(key) 

2.
```python
def listen(event):
    if event.event_type == "down" and event.name in string.ascii_lowercase:
        print(event.name) 

keyboard.hook(listen) 
keyboard.wait() 
```

**Comment by isaksc2** [comment]
thank you very much

**Comment by xingzhuimeteorite** [comment]
thank you very much  ，， it is very good.
