### ISSUE TITLE
Print Key names???

### ISSUE THREAD

**Issue by PythonUser913** [boppreh/keyboard#452]
Could it be possible to add something like print(keyboard.Key_names)for  printing all key names because I can't find a web site with all the key names. I would really like to have this feature because it would be useful for learning all the key names for this module

**Comment by boppreh** [comment]
It's not cross-platform yet, but if you are on Windows you can do the following:

```
import keyboard
keyboard._winkeyboard._setup_name_tables()
print(keyboard._winkeyboard.from_name.keys())
```

This will give a list of all key names the system could find. The `from_name` keys maps from those names to a tuple `(scan_code, virtual_key_code, is_extended, modifiers)`, which is used by the higher level functions.

On my system the code above prints:

```
dict_keys(['esc', '1', '!', '¡', '2', '@', '²', '3', '#', '³', '4', '$', '¤', '5', '%', '€', '6', '^', '¼', '7', '&', '½', '8', '*', '¾', '9', '(', '‘', '0', ')', '’', '[', '-', '{', '«', ']', '=', '}', '»', 'backspace', 'tab', 'q', 'Q', 'ä', 'w', 'W', 'å', 'e', 'E', 'é', 'r', 'R', '®', 't', 'T', 'þ', 'z', 'Y', 'Z', 'y', 'æ', 'u', 'U', 'ú', 'i', 'I', 'í', 'o', 'O', 'ó', 'p', 'P', 'ö', ';', ':', '¶', '+', '×', 'enter', 'ctrl', 'left ctrl', 'right ctrl', 'a', 'A', 'á', 's', 'S', 'ß', 'd', 'D', 'ð', 'f', 'F', 'g', 'G', 'h', 'H', 'j', 'J', 'k', 'K', 'l', 'L', 'ø', '`', '~', "'", 'acute/cedilla', '"', '´', '\\', '|', '¬', 'shift', 'left shift', '/', '?', '¿', 'ü', 'x', 'X', 'c', 'C', '©', 'v', 'V', 'b', 'B', 'n', 'N', 'ñ', 'm', 'M', 'µ', ',', '<', 'ç', '.', '>', '_', '¥', 'right shift', 'nummult', 'print screen', 'alt', 'left alt', 'right alt', 'space', 'caps lock', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'pause', 'num lock', 'scroll lock', 'break', 'home', 'up', 'page up', 'left', 'clear', 'right', 'end', 'down', 'page down', 'insert', 'delete', 'num decimal', '<00>', 'help', 'f11', 'f12', 'left windows', 'right windows', 'erase eof', 'menu', 'zoom', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', '\x03', 'control-break processing', 'ime hangul mode', 'ime junja mode', 'ime final mode', 'ime kanji mode', 'ime convert', 'ime nonconvert', 'ime accept', 'ime mode change request', 'select', 'print', 'execute', 'sleep', 'separator', 'decimal', 'right menu', 'browser back', 'browser forward', 'browser refresh', 'browser stop', 'browser search key', 'browser favorites', 'browser start and home', 'volume mute', 'volume down', 'volume up', 'next track', 'previous track', 'stop media', 'play/pause media', 'start mail', 'select media', 'start application 1', 'start application 2', 'ime process', 'attn', 'crsel', 'exsel', 'play', 'reserved ', 'pa1', 'alt gr'])
```

**Comment by HaujetZhao** [comment]
> It's not cross-platform yet, but if you are on Windows you can do the following:
> 
> ```
> import keyboard
> keyboard._winkeyboard._setup_name_tables()
> print(keyboard._winkeyboard.from_name.keys())
> ```
> 
> This will give a list of all key names the system could find. The `from_name` keys maps from those names to a tuple `(scan_code, virtual_key_code, is_extended, modifiers)`, which is used by the higher level functions.
> 
> On my system the code above prints:
> 
> ```
> dict_keys(['esc', '1', '!', '¡', '2', '@', '²', '3', '#', '³', '4', '$', '¤', '5', '%', '€', '6', '^', '¼', '7', '&', '½', '8', '*', '¾', '9', '(', '‘', '0', ')', '’', '[', '-', '{', '«', ']', '=', '}', '»', 'backspace', 'tab', 'q', 'Q', 'ä', 'w', 'W', 'å', 'e', 'E', 'é', 'r', 'R', '®', 't', 'T', 'þ', 'z', 'Y', 'Z', 'y', 'æ', 'u', 'U', 'ú', 'i', 'I', 'í', 'o', 'O', 'ó', 'p', 'P', 'ö', ';', ':', '¶', '+', '×', 'enter', 'ctrl', 'left ctrl', 'right ctrl', 'a', 'A', 'á', 's', 'S', 'ß', 'd', 'D', 'ð', 'f', 'F', 'g', 'G', 'h', 'H', 'j', 'J', 'k', 'K', 'l', 'L', 'ø', '`', '~', "'", 'acute/cedilla', '"', '´', '\\', '|', '¬', 'shift', 'left shift', '/', '?', '¿', 'ü', 'x', 'X', 'c', 'C', '©', 'v', 'V', 'b', 'B', 'n', 'N', 'ñ', 'm', 'M', 'µ', ',', '<', 'ç', '.', '>', '_', '¥', 'right shift', 'nummult', 'print screen', 'alt', 'left alt', 'right alt', 'space', 'caps lock', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'pause', 'num lock', 'scroll lock', 'break', 'home', 'up', 'page up', 'left', 'clear', 'right', 'end', 'down', 'page down', 'insert', 'delete', 'num decimal', '<00>', 'help', 'f11', 'f12', 'left windows', 'right windows', 'erase eof', 'menu', 'zoom', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', '\x03', 'control-break processing', 'ime hangul mode', 'ime junja mode', 'ime final mode', 'ime kanji mode', 'ime convert', 'ime nonconvert', 'ime accept', 'ime mode change request', 'select', 'print', 'execute', 'sleep', 'separator', 'decimal', 'right menu', 'browser back', 'browser forward', 'browser refresh', 'browser stop', 'browser search key', 'browser favorites', 'browser start and home', 'volume mute', 'volume down', 'volume up', 'next track', 'previous track', 'stop media', 'play/pause media', 'start mail', 'select media', 'start application 1', 'start application 2', 'ime process', 'attn', 'crsel', 'exsel', 'play', 'reserved ', 'pa1', 'alt gr'])
> ```

I think this worth added to the README example part.
