### ISSUE TITLE
Unicode Characters not being typed properly on Linux

### ISSUE THREAD

**Issue by SpikeVN** [boppreh/keyboard#474]
OS: Kali Linux Rolling (I think that all Distros are affected)
Interpreter: CPython 3.9.6, running in IDLE with root permission.
Code: 
```py
import keyboard

keyboard.write("â")
# Cannot use the parameter exact=True, because when typing my program listen to input
# too and it (currently) cannot be stopped.
```
It doesn't work on Linux, but it worked flawlessly on Windows. Wierd.
Traceback: 
```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/keyboard/__init__.py", line 854, in write
    scan_code, modifiers = next(iter(entries))
StopIteration
```

**Comment by Ianm22** [comment]
Same here and I tried with multiple OS: ArchLinux (GNOME), Manjaro (GNOME), KDE Neon (KDE) and Fedora (GNOME).
Python Version: 3.9.6

All with root permissions and I had the same problem.
