### ISSUE TITLE
Is there any way to stop read_hotkey() programmatically?

### ISSUE THREAD

**Issue by zixiao-bios** [boppreh/keyboard#478]
[`read_hotkey()`](https://github.com/boppreh/keyboard#keyboard.read_hotkey) will block and wait user presses and releases a hotkey, but is there any way to stop it with program?

I'm working on a program which allows users to input a hotkey from keyboard, and push a button to cancel hotkey input. So I need to stop blocking when the "cancel" button is pushed.

I have read whole API doc but can't find a method to do it. Is anyone has an idea? Or maybe I miss something in the doc?

**Comment by boppreh** [comment]
Right now there's no cancelleable version of `read_hotkey`. The current implementation is simple enough that it might be worth rewriting it to fit your need.

However I think it's a pretty good idea in general, also for other functions like `wait`. What would be your preferred implementation?

I'm leaning towards [cancellation tokens](https://docs.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads), which you pass to canceallable functions, and can activate if want to tell that function to stop.

**Comment by zixiao-bios** [comment]
> 
> 
> Right now there's no cancelleable version of `read_hotkey`. The current implementation is simple enough that it might be worth rewriting it yourself to fit your need.
> 
> However I think it's a pretty good idea in general, and worth implementing in the library, also for other functions like `wait`. What would be your preferred implementation?
> 
> I'm leaning towards [cancellation tokens](https://docs.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads), which you pass to canceallable functions, and can activate if want to tell that function to stop.

Thank you for your reply! I'm new to programming so I implemented it in a very simple way:
```python
# parameter stop_blocking is used to control whether the function continues to block
def read_hotkey(suppress=True, stop_blocking=[False]):
    queue = _queue.Queue()
    fn = lambda e: queue.put(e) or e.event_type == KEY_DOWN
    hooked = hook(fn, suppress=suppress)

    while True:
        event = None
        try:
            # use get() with timeout, so that it has an opportunity to check the value of stop_blocking
            event = queue.get(timeout=0.1)
        except _queue.Empty:
            pass

        if event is not None and event.event_type == KEY_UP:
            # read a hotkey and return normally
            unhook(hooked)
            with _pressed_events_lock:
                names = [e.name for e in _pressed_events.values()] + [event.name]
            return get_hotkey_name(names)

        if stop_blocking[0]:
            # get ths stop_blocking signal and stop blocking
            unhook(hooked)
            return ""
```
And when you want to stop blocking, just set `stop_blocking[0] = True` outside the function.
I'm sure that this is not a good idea, but it works for me at least.😂

**Comment by boppreh** [comment]
That's exactly what I was suggesting! Not a bad idea at all.

You could make the solution a bit cleaner by using a [`threading.Event`](https://docs.python.org/3/library/threading.html#event-objects) object instead of an array holding a boolean. This would help communicating to future programmers (including yourself in the future) how this feature works; but the actual bytecode that will be executed is practically identical.

https://github.com/boppreh/keyboard/blob/master/keyboard/__init__.py#L216

**Comment by zixiao-bios** [comment]
> 
> 
> That's exactly what I was suggesting! Not a bad idea at all.
> 
> You could make the solution a bit cleaner by using a [`threading.Event`](https://docs.python.org/3/library/threading.html#event-objects) object instead of an array holding a boolean. This would help communicating to future programmers (including yourself in the future) how this feature works; but the actual bytecode that will be executed is practically identical.
> 
> [I actually use something similar in the hotkey hooks](https://github.com/boppreh/keyboard/blob/master/keyboard/__init__.py#L768) with a custom class and adding extra attributes, but in that case it's not justified and feels hacky. The new version won't have that anymore.

Yes, an array holding a boolean is confusing. Thanks for your suggestion, it helps a lot!

**Comment by boppreh** [comment]
Good luck!

I'll go ahead and close the ticket. The answer to the title question is "not yet, but it's planned".
