### ISSUE TITLE
Alt keys aren't detected properly

### ISSUE THREAD

**Issue by Hyphen-ated** [boppreh/keyboard#48]
As mentioned in a thread about a different issue:

When I run this program:
```Python
import keyboard
def info(event):
    print (event.name + ", " + str(event.scan_code) + ", " + event.event_type)
keyboard.hook(info)
keyboard.wait("esc")
```
and press left alt, I see "left alt, 56, down" as expected. When I release left alt, I see
left alt, 56, up
left alt, 56, down
left alt, 56, up

When I press and release right alt, I see:
left alt, 56, down
left alt, 56, up

I went looking for someplace else to test my keyboard events, and found https://w3c.github.io/uievents/tools/key-event-viewer.html
When I press and release left alt and then right alt in this tool, it looks like this:
http://i.imgur.com/FNNKpZn.png
It's not showing either problem.

I was slightly surprised that it was reporting my numlock status in this other tool. I tried turning off numlock to see if that made any difference to my "keyboard" problem. It didn't.

Windows 8.1
Tested on Python 2.7.13 and 3.6.0
keyboard 0.9.12

**Comment by Hyphen-ated** [comment]
I inserted
```Python
print "{} {} {} {}".format(event_type, vk, scan_code, is_extended)
```
at https://github.com/boppreh/keyboard/blob/master/keyboard/_winkeyboard.py#L368

When I press left alt, this prints
down 164 56 0
up 164 56 0
down 164 56 0
up 164 56 0

When I press right alt, this prints
down 165 56 1
up 165 56 1
down 164 56 0
up 164 56 0

When I press any other key, it only prints two lines.
I'm using a US keyboard.

**Comment by Hyphen-ated** [comment]
The alt key is kind of weird, so maybe it's okay to just say "you know what, you can't bind things directly to the alt key".
But I think it's pretty important for key combos involving alt to work.
```Python
def okay():
    print "okay"
keyboard.add_hotkey('alt+q', okay)
```
This hotkey is triggered once when I press alt+q with the left alt key. It is not triggered when I use the right alt key.

**Comment by Enteleform** [comment]
> **OS:** Windows 10.0.15063 x64
> **Python:** 3.6.2
> **Keyboard:** Lenovo ThinkPad Compact USB Keyboard

My left-alt key is detected correctly, but the right-alt key is not detected at all.
It is, however, detected by the online `key-event-viewer` utility that @Hyphen-ated linked to.

All other modifiers work as expected and work on both left & right sides.

**Comment by boppreh** [comment]
I could never reproduce the issue, but detection of alt gr has been greatly improved in the latest version.  If anyone who is having this issue could try the master branch, I would greatly appreciate.

**Comment by Hyphen-ated** [comment]
When I run my two test programs from the top of this thread on master, pressing left alt makes them correctly print
> alt, 56, down
alt, 56, up

and 
>down 164 56 0
up 164 56 0

respectively. 

Pressing right alt makes them both print nothing.

**Comment by boppreh** [comment]
Thank you for the quick answer!

Is your right alt a normal alt key, or an alt gr? Does it work on other applications? Sometimes keys are not mapped at all.

**Comment by Hyphen-ated** [comment]
It's a normal alt key and it works in other applications

**Comment by boppreh** [comment]
I've looked everywhere and there's only one thing left to test: on `_winkeyboard.py` there's a check `if vk == 165: return True` (currently line 493) to skip a duplicated event in case of AltGr. Can you try commenting out that check to see if right alt prints something?

**Comment by Hyphen-ated** [comment]
When I remove that check, I get what looks like it might be correct behavior:

> right alt, 56, down
right alt, 56, up

and
> down 165 56 1
up 165 56 1

**Comment by Hyphen-ated** [comment]
When I run the test program from the top of this thread and press+release left alt, then right alt, I get this:
alt, 56, down
alt, 56, up
right alt, 56, down
right alt, 56, up

This looks correct

**Comment by boppreh** [comment]
Great, thank you. I'm finally closing this issue, but feel free to comment on it again and I'll reopen if you think some problem persists.
