### ISSUE TITLE
The modifier keys don't work properly on BigSur

### ISSUE THREAD

**Issue by takeyamayuki** [boppreh/keyboard#488]
First of all, thanks for the great library.

This is a bug report on BigSur.
On macOS BigSur 11.5.2, the modifier keys (ctrl, option, shift, cmd) don't work properly. 

- The right shift on my macbookpro keyboard works, but it works differently than windows. If you press the key all the way down, it will only be recognized the first time. If it is an external keyboard, it is not even recognized.

- As for the command keys, only the left cmd was recognized as win,cmd, but it behaved the same as the right shift on both the external keyboard and the built-in keyboard of the macbookpro.

- Option does not work when I try it as alt.
- Function keys and text keys work as usual.

Here is the code I tried.
```python
import keyboard
hotkey='XXX'

while True:
    keyboard.wait(hotkey)
    print('hotkey was pressed! Waiting on it again...')
````
MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
BiguSur 11.5.2
Python 3.7.5
keyboard 0.13.5

**Comment by Luidenka-Golden** [comment]
Me too. I have the same problem. I use an is_pressed to detect, but Ctrl, Alt, Cmd can't detect.
The code:

`import keyboard
if keyboard.is_pressed('Control'):
    print('hello world')`

MacBook Air (13-inch ,2020, 2 Thunderbolt 3 Ports)
BigSur 11.6
Python 3.9.6
keyboard 0.13.5
