### ISSUE TITLE
Syntax error since last version

### ISSUE THREAD

**Issue by fridde** [boppreh/keyboard#503]
Is it just me or has anyone else noticed that the package is broken since last commit?

The syntax error in [this commit](https://github.com/boppreh/keyboard/commit/4840539ff7dcf017f5d85811ce4d9c74727cd299) seems pretty obvious (the "quotations" are" wrong), but maybe it's just me who can't install this package anymore.

Can anyone revert this?

**Comment by boppreh** [comment]
It's fixed now, thanks for letting me know.

That shows me not to make arbitrary changes on a notebook without Linux to test, even if they are just different messages.

**Comment by fridde** [comment]
Thanks! That was a quick response.

I am not too familiar with the internals of the installation process, but it seemed to me that this was OS independent. Running ```pip install .``` parses through all files included in the package, irregardless of the branch being reached.

You probably didn't notice because you did a "hot swap" and thus the parser never saw what you wrote.
