### ISSUE TITLE
Exiting the keyboard.wait() loop with code?

### ISSUE THREAD

**Issue by BrandonRaggett** [boppreh/keyboard#57]
I understand that CTRL+C will terminate the thread, but I would like to quit both GTK and keyboard with the same function. Did I miss something?

**Comment by boppreh** [comment]
I don't know about GTK, but `keyboard.wait()` is used to block forever. If you want to block for a limited time, and unblock via code, you could try one of the [lock objects](https://docs.python.org/3/library/threading.html#lock-objects) from the standard [`threading`](https://docs.python.org/3/library/threading.html) library.

Does that help?

**Comment by BrandonRaggett** [comment]
That should help, I will review your code further and try to come up with a solution. Thank you.

**Comment by BrandonRaggett** [comment]
As the threads that you used were daemon threads, they close when only they are left. I just discovered that calling keboard.wait() isn't needed as importing keyboard starts the worker threads, and calling Gtk.main() acts like keyboard.wait() does. 
Thank you for creating this library, and providing some great material to learn from!
