### ISSUE TITLE
Directional hotkeys cause ValueError spam when everything but hotkey is pressed

### ISSUE THREAD

**Issue by henkka95** [boppreh/keyboard#59]
Using directional arrows ('up', 'down', 'left', 'right') as hotkeys  with:
`keyboard.add_hotkey('left', print, args=['Hi mum!'])`

Causes following error:
`Traceback (most recent call last):
  File "path\keyboard\_generic.py", line 23, in invoke_handlers
    if handler(event):
  File "path\keyboard\__init__.py", line 296, in handler
    unexpected = not any(matches(event, part) for part in steps[state.step])
  File "path\keyboard\__init__.py", line 296, in <genexpr>
    unexpected = not any(matches(event, part) for part in steps[state.step])
  File "path\keyboard\__init__.py", line 152, in matches
    return matched_name or _os_keyboard.map_char(normalized)[0] == event.scan_code
  File "path\keyboard\_winkeyboard.py", line 447, in map_char
    raise ValueError('Key name {} is not mapped to any known key.'.format(repr(name)))
ValueError: Key name 'down' is not mapped to any known key.`
(path = my python installation path.)

In windows every time I press something else than my hotkey. 

It's minor issue as it program still functions correctly, but it's still quite irritating.

**Comment by boppreh** [comment]
Hi @henkka95 

I can't reproduce this issue, and this is a key that should be mapped by virtual key code, which should work regardless of internationalization or keyboard layout. Is there anything unusual about your setup?

Could you please try the following code, to print all the native key names?

	from keyboard import _winkeyboard
	_winkeyboard._setup_tables()
	from pprint import pprint
	pprint(_winkeyboard.to_scan_code)

And to see what names are being given to your keys, `python -m keyboard` then press the left key.

Thank you

**Comment by boppreh** [comment]
Actually, nevermind, this is probably a repeat of #56. Could you try the master version from github, instead of the latest release?

**Comment by henkka95** [comment]
Yeah using masterversion issue was gone. Thanks

**Comment by boppreh** [comment]
Thanks. for the report anyways. It's good to have an idea what features people are using.

I'm doing a refactoring now to properly expose the internals for low level uses, and will be releasing a new version after.
