### ISSUE TITLE
Error in doc: add_abbreviation

### ISSUE THREAD

**Issue by cjbarroso** [boppreh/keyboard#61]
The add_abbreviation doc shows that the parameter match_suffix "Defaults to false, only whole words are checked.".

The method prototipe shows "match_suffix=True", and the behaviour is exactly that. I'm not shure what is the intended behaviour (If you ask me, I prefer False as default).

**Comment by boppreh** [comment]
Fixed, thanks. Now `match_suffix` defaults to False.
