### ISSUE TITLE
Question regarding the usage of keyboard. hook()

### ISSUE THREAD

**Issue by Moondra** [boppreh/keyboard#63]
I'm not exactly sure how to correctly implement keyboard. hook(). 
The method `hook` seems to continuously takes in key_presses and info as the 4 attributes below. 
I'm still a novice with regards to programming, so not sure if I used  a callback function correctly, but I was trying to print keypresses as they occur. And if I press the key 'down', I would print 'x'. 

```
def printer(name, scan_code, time, event_type):
    print (name)
    if name == 'down':
        print('x')

keyboard.hook(printer)
```

However this is ending up in the error, 

 `printer() missing 3 required positional arguments: 'scan_code', 'time', and 'event_type'`

Thank you.

**Comment by boppreh** [comment]
Hi @Moondra ! You are almost there.

The callback should take a single argument, a "keyboard event" object. This is why the error says "3 required positional arguments": because `hook` only passed one argument (the event object), and your function expected four.

It should look more like this (untested):

```
def printer(event):
    print (event.name)
    if event.name == 'down':
        print('x')

keyboard.hook(printer)
```

But note this will print twice, once for the KEY_DOWN event and once for the KEY_UP event, so you may want to filter by `event_type` too.

Good luck!

**Comment by Moondra** [comment]
Thank you so much. Works perfectly. 

I modified it to filter out KEY_UP events (Thanks for the tip)

```
def printer(event):
    print (event.name)
    print (event.event_type)
    if event.name == 'down' and event.event_type == 'up':
        print('x')

keyboard.hook(printer)
```

If you have time, I would add your example (you can even use mine) in the docs, as it would really help 
 other newcomers such as myself.  This seems to be a very polished module and will def gain more popularity as time goes on. 
 Thank you so much for your hard work.

**Comment by 2no1** [comment]
Hello, im still very new to python and i find your module very interesting but the documentation is not very "noob friendly". 
```

import keyboard

event = keyboard.record(until='escape')
keys=[]
def key(event):
	if event.event_type == 'down':
		keys.append(event)
keyboard.hook(key)
print(keys)
```
The print(keys) prints out an empty list. Wasnt it suppost to append the down keys and print them? Sorry in advanced if my mistakes are pure python errors or logic ones.

Thank you.

**Comment by boppreh** [comment]
@Moondra Good idea, I'll add your code to the examples directory.

@2no1 `keyboard.hook` is an asynchronous function. The program executes it then proceeds to the next function (print) almost instantaneously. At this point the list is still empty.

Think about it this way: *when* do you want to print the list? After every event (put inside the `key` function)? After *n* events (put inside the `key` function inside an `if len(keys) ...`)? After *n* seconds (leave it outside, but put a `time.sleep` between `keyboard.hook` and the `print`)?

**Comment by 2no1** [comment]
@boppreh Thank you so much for your answer, and thank you for offering your help, i was able to understand a lil bit more the hook function and my code now looks like this:

```
keys=[]
def key(event):
	if event.event_type == 'down':
		keys.append(event)
keyboard.hook(key)
time.sleep(5)
print (keys)
```
But now i have a question about printing the keys, they are printed in the list form, to print just the key that was pressed (ex. [KeyboardEvent(1 down)] will just print 1) will hotkeys be the best solution or should i convert the list to a string and manipulate the string? I know i can get i done with a bunch of if..elif but i dont thank thats the most reliable solution. 

Thank you.

**Comment by boppreh** [comment]
It's printing the entire event because that's what was added to the list: `keys.append(event)`. If you want a list of only the key names, you can do `keys.append(event.name)`.

**Comment by boppreh** [comment]
Oh, and if you want to print the keys as they are are pressed you can simply do `print event.name` inside your `key` function.

This is similar to what the module does when you run it directly: `python -m keyboard`

I'm closing this issue since the original problem seems to be gone, but feel free to continue posting here, or send me an email.
