### ISSUE TITLE
"RuntimeError: dictionary changed size during iteration"

### ISSUE THREAD

**Issue by Moondra** [boppreh/keyboard#64]
Hi,

I've noticed that when I run this code:
```


import keyboard


while 1:
    
    if keyboard.is_pressed('down'):
        print ('yes')

```

If I press anything else besides 'down' I get the following runtimeerror, which exits me out of my program.

```Traceback (most recent call last):
  File "C:/Users/Moondra/AppData/Local/Programs/Python/Python36/testing_keyboard3.py", line 6, in <module>
    if keyboard.is_pressed('down'):
  File "C:\Users\Moondra\AppData\Local\Programs\Python\Python36\lib\site-packages\keyboard\__init__.py", line 171, in is_pressed
    for event in _pressed_events.values():
RuntimeError: dictionary changed size during iteration
```

Is this a normal behavior? I was expecting no response. 

Thank you.

**Comment by boppreh** [comment]
This is a bug, but triggered by this unusual line in your code: `while 1:`

This will constantly verify if the key is pressed, using 100% of the CPU. You should put a `time.sleep` between executions, or use use a more appropriate function from the library, such as `add_hotkey`. Try:

    import keyboard
    def print_yes():
        print('yes')
    keyboard.add_hotkey('down', print_yes)

**Comment by Moondra** [comment]
Thanks the add_hotkey method works great.
