### ISSUE TITLE
Suggestion for hotkeys docs

### ISSUE THREAD

**Issue by Moondra** [boppreh/keyboard#65]
I had no idea 57 represented a keyboard scancode. I was thinking your want to showcase numerical hot keys to print messages. It was when I was typing this message, that I noticed something being outputted in the shell from the corner of my eye, lol. So adding some sort of comment like below might be useful for newcomers.

`

"Here are some of the different ways to represent spacebar:

keyboard.add_hotkey(57, print, args=['space was pressed'])   # Here 57 REPRESENTS the keyboard code for spacebar; so you will be pressing 'spacebar', not '57'  to activate the print function. 

keyboard.add_hotkey('')........"

**Comment by boppreh** [comment]
Thank you for your suggestion, and sorry it took so long to apply it. It'll be visible after merging the branch.
