### ISSUE TITLE
Question regarding  keyboard.read_key

### ISSUE THREAD

**Issue by Moondra** [boppreh/keyboard#66]
In the docs it says:

'Blocks until a keyboard event happens, then returns that event.'

Is this the main thread it's blocking? 
If so I'm trying to implement something like block thread until 'd' is pressed. 

I tried to replicate the coding frame included in the docs
keyboard.read_key(filter =lambda e: True), 

as such:

```
def pressed():
    if keyboard.is_pressed('d') == True:
        return True

keyboard.read_key(filter =lambda pressed: True)
```

But it seems I"m calling the method incorrectly. 

Thank you.

**Comment by boppreh** [comment]
The thread that is blocked is the current thread (the one that called the function).

The problem in your code is that you are not using the `pressed` function you created. `lambda pressed: True` is an anonymous functions that takes a parameter named "pressed", unrelated to the function you created. You should use the function directly: `keyboard.read_key(filter=pressed)`.

But note that this filter function is supposed to take one parameter, namely the event to be filtered. So:

```
def pressed(event):
    if keyboard.is_pressed('d') == True:
        return True
```

(note the `(event)` parameter.

Or simply:

```
def pressed(event):
    return event.name == 'd'
```

Or

```
keyboard.read_key(filter=lambda e: e.name == 'd')
```
