### ISSUE TITLE
Linux: multiple keyboards

### ISSUE THREAD

**Issue by caenyon** [boppreh/keyboard#7]
I had some problems getting keyboard events and found out that the problem was caused by these lines (nixkeyboard.py, line 65):
```
paths = glob('/dev/input/by-path/*-event-kbd')
print(paths)
if paths:
    device = EventDevice(paths[0])
```

This code assumes that there's only one input device matching `*-event-kbd`. If there are multiple matches, it selects the first. However, there are three matches on my machine:
```
paths = ['/dev/input/by-path/pci-0000:00:14.0-usb-0:3.2.1:1.1-event-kbd',  # ???
         '/dev/input/by-path/pci-0000:00:14.0-usb-0:3.2.1:1.0-event-kbd',  # usb keyboard
         '/dev/input/by-path/platform-i8042-serio-0-event-kbd']  # laptop keyboard
```

I tested that the second device is my usb keyboard and the third device is the keyboard of my laptop. I don't know about the first device.

I think the library should read input from all keyboard input devices (or even better, allow the user to specify which devices to read from). What do you think?

**Comment by boppreh** [comment]
> I think the library should read input from all keyboard input devices (or even better, allow the user to specify which devices to read from). What do you think?

Great idea. I think reading from all is the solution for now because it doesn't require any setup code to use the library. I'll update shortly.

**Comment by boppreh** [comment]
The code for aggregating multiples sources is now the master branch, for both mouse and keyboard. I'll release a version later.

**Comment by boppreh** [comment]
Since this issue is so old I'll be closing it before hearing your feedback, but feel free to comment if you think the solution could be improved.
