### ISSUE TITLE
Word listeners and symbols

### ISSUE THREAD

**Issue by glitchassassin** [boppreh/keyboard#70]
The word listener uses upper() to capitalize keys if it detects that the shift key is pressed. This works great for letters, but it means it can't recognize "@@".

This example doesn't work for me:

    # Type @@ then press space to replace with abbreviation.
    keyboard.add_abbreviation('@@', 'my.long.email@example.com')

**Comment by boppreh** [comment]
On the master branch, the backend now reports key event names according to shift/ctrl/alt gr status. Word listeners don't need to worry about shift state anymore. This also allows abbreviations with composite characters such as alt gr+s for ß, since these are also handled by the backend.

**Comment by nitanmarcel** [comment]
@boppreh Same happens with the latest version. I'm trying to make a script that could help me to convert :name: to emojis but is not working. Other symbols seem to work, but : and @ doesn't seem to work for me
