### ISSUE TITLE
Program blocks on starting listening thread when launching in PyDev/Eclipse

### ISSUE THREAD

**Issue by Doom8890** [boppreh/keyboard#74]
Hey everyone, today I started messing around with `keyboard`, however I found out that this simple program blocks on launching listening thread. I'm using PyDev, but it works fine in Python IDLE.

```python
import keyboard

def key_hook(event):
    print(("Name: {0}\n"
           "Scan code: {1}\n"
           "Timestamp: {2}\n"
           "Type: {3}").format(event.name,
                               event.scan_code,
                               event.time,
                               event.event_type))


if __name__ == '__main__':
    print("Test")
    keyboard.on_press(key_hook)
```
Here's the callstack: 
![capture](https://user-images.githubusercontent.com/17911579/27984025-6ab942fe-63cb-11e7-96f0-86c37abb39ee.PNG)

And here's the line where it starts to block:
![capture2](https://user-images.githubusercontent.com/17911579/27984040-92b4074e-63cb-11e7-83d8-77c672aa8ac2.png)

I'm really not sure what causes this, aside from Eclipse somehow interfering with threads. Any ideas?

**Comment by Doom8890** [comment]
Never mind, it seems you need to make sure main thread is alive in PyDev(by placing while loop or something similar). It seems PyDev thinks the program is finished running even though there are other threads active.

**Comment by glitchassassin** [comment]
That's expected behavior with threading.

You can use a `keyboard.wait()` to keep the thread running. Otherwise it terminates after creating the listener.

**Comment by Doom8890** [comment]
Indeed, that's what I ended up doing in the end.  The part where it worked in IDLE without that, but not in PyDev confused me. I guess this can be closed now.
