### ISSUE TITLE
problem with underscore in abbreviations

### ISSUE THREAD

**Issue by tkossak** [boppreh/keyboard#76]
When i create abbreviation `keyboard.add_abbreviation('ab', 'ab_cd')` and then enter `ab ` in terminal, the text is replaced with `abcd` instead of `ab_cd` and my terminal font is decreased. It seems like the keyboard sends `CTRL+-` instead of `SHIFT+-`. Any way to fix this?

Linux Mint 18.1 Cinnamon x64
Gnome Terminal 3.18.3
Python 3.6.1
keyboard 0.9.13

**Comment by boppreh** [comment]
This should now be fixed https://github.com/boppreh/keyboard/commit/6a7032b0d0fb494984f13a2e0bd1b91d20c25117 , along with many other bugs relating to mapping names -> keyboard combinations.

**Comment by tkossak** [comment]
There is still a bug, only different. After creating above shortcut when i write `ab` in terminal and press SPACE, the text is replaced with `a_cd` instead of `ab_cd`. I tried latest version from github.
