### ISSUE TITLE
How to hold and release mouse?

### ISSUE THREAD

**Issue by DanMossa** [boppreh/keyboard#77]
I see a mouse.release but no hold or anything like that

**Comment by glitchassassin** [comment]
Try `mouse.press()`.

**Comment by boppreh** [comment]
@glitchassassin is correct, 'press' is the function you are looking for. However I think an alias wouldn't hurt here.

**Comment by DanMossa** [comment]
Much appreciated guys!. 
@boppreh
Is there any reason to not completely change it instead of just adding an alias?

**Comment by glitchassassin** [comment]
Backwards compatibility.

**Comment by DanMossa** [comment]
I created pull request #78
