### ISSUE TITLE
Held-down keys are not suppressed

### ISSUE THREAD

**Issue by Mistyazur** [boppreh/keyboard#83]
Code: `keyboard.add_hotkey("Capslock", lambda: print("123"), suppress=True, timeout=10)`

If I hit capslock shortly, it works as my expect,  capslock was not send to system.
But if i holding the capslock for several secs,  only first KEY_DOWN message was suppressed and the next several KEY_DOWN messages passed to the system. After that Capslock indicator turned on and couldn't turn off by hitting capslock until i removed the hotkey.
Is that bug?

**Comment by boppreh** [comment]
Bug, and seems to happen to keys other than "Capslock" too. I'll investigate a solution.

Also note that "timeout" only makes sense for multi-step hotkeys, like `ctrl+a, b` (press and hold `ctrl+a`, release, press `b`). I'll try to add an error against that in the future to avoid confusion.

**Comment by Mistyazur** [comment]
Thank you.
I tested out that if i use statsh_state() in the hotkey callback, everything was right.
I don't know why, but hope it will help you to fix it
```
def test():
    state = keyboard.stash_state()
    print("123")
    return

keyboard.add_hotkey("Capslock", lambda: test(),
                    suppress=True)
```

**Comment by boppreh** [comment]
That does help, thank you.

I'm working on a rewrite of the key suppression system. The current one is clever, but far too complicated, and has presented hard-to-fix bugs before.

**Comment by Enteleform** [comment]
This also affects modifiers that are held down.  

For example:  

```python
import keyboard
from datetime import datetime

hotkeys = ["ctrl+a", "ctrl+v"]

for hotkey in hotkeys:
    keyboard.add_hotkey(hotkey, print, args=[datetime.now(), hotkey], suppress=True)

while True:
    pass
```

&nbsp;  
If you press:  

- <kbd>Ctrl Down</kbd>
- <kbd>A</kbd>
- <kbd>V</kbd>
- <kbd>Ctrl Up</kbd>

<kbd>A</kbd> does not have an immediate effect and forwards the key event to `print` as expected. &nbsp; However, when <kbd>V</kbd> is pressed, the `select all` command of <kbd>A</kbd> is executed along with the `paste` command of <kbd>V</kbd>.

**Comment by marczellm** [comment]
is my problem related to this? my problem is that specifying a hotkey `'ctrl, ctrl'` also triggers when holding ctrl

**Comment by boppreh** [comment]
I'm happy to announce these two issues has been fixed by a rewrite of the suppression system. It's a lot more complex than it sounds, but I think it's doing the sensible thing now. The new version is available on the master branch until I make a full release.

Note that pressing "<kbd>ctrl</kbd>+<kbd>a</kbd>+<kbd>v</kbd>" (without releasing <kbd>a</kbd>), allows the hotkey to pass through, because it's a valid hotkey that's not being blocked. I'm still on the fence on what the correct behavior is in this case.

**Comment by xoiga123** [comment]
I just want to add something in because this has helped me a lot: If you have multiple `read_hotkeys()` in a run, it's always good to have `stash_state()` between them to get rid of pressed keys.

I'm sorry for replying to a closed issue but only this one helped me. Thank you guys!
