### ISSUE TITLE
strange exception in keyboard library << python

### ISSUE THREAD

**Issue by liors619** [boppreh/keyboard#86]
I want to wait until the button 'q' is pressed

this is my code:

    import keyboard
    while True:
            if keyboard.is_pressed('q'):
                print('q is pressed')
                break #finishing the loop

and this is the exception i got:

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
        self.run()
      File "C:\Python27\lib\threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "C:\Python27\lib\site-packages\keyboard\__init__.py", line 134, in listen
        _os_keyboard.listen(self.queue, _key_table.is_allowed)
      File "C:\Python27\lib\site-packages\keyboard\_winkeyboard.py", line 423, in listen
        keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, NULL, NULL)
    ArgumentError: argument 2: <type 'exceptions.TypeError'>: expected CFunctionType instance instead of CFunctionType

what is the problem?

**Comment by boppreh** [comment]
Thank you for the report. I can't reproduce, but something similar happened in the `mouse` library, so I have a possible fix at hand.

Can you check if the `master` branch fixes the error for you? You can get the newest version with 

`git clone https://github.com/boppreh/keyboard.git`

, or if you don't have Git, try this changing this line: https://github.com/boppreh/keyboard/commit/5f8735385ee052f681a45188beefd661f9e731ae

Also, the logic of "wait until a key is pressed" is implemented in [`keyboard.wait("q")`](https://github.com/boppreh/keyboard#keyboard.wait).

Thank you for the report.

**Comment by liors619** [comment]
about keyboard.wait("q") i got it late lol
but it's made the same problem

i changes the line u said and the problem got fixed
thank you!

**Comment by boppreh** [comment]
Awesome! The fix will be available in the next release. Thank you for the report and testing the fix.
