### ISSUE TITLE
Suggestion for keyboard.record

### ISSUE THREAD

**Issue by softuser25** [boppreh/keyboard#87]
Suggestion: Add keyboard.record(time=x)
When started it records for specific amount of time.

**Comment by boppreh** [comment]
Good idea.

To allow more flexibility in the stopping condition, I'm thinking of adding `start_recording()` and `stop_recording`, so your time example would be:

```
start_recording()
sleep(10)
events = stop_recording()
```

This would also allow `start_recording` to stream events.

I know it's a lot more than just `time=x`, but does this alternative sound good to you?

**Comment by softuser25** [comment]
Yeah,even better!

**Comment by boppreh** [comment]
Implemented by https://github.com/boppreh/keyboard/commit/74163f23c5c9a93131d51258c0aa6f0d1b986138 , example at https://github.com/boppreh/keyboard/blob/master/examples/10_second_macro.py .

Thank you for the suggestion!

**Comment by boppreh** [comment]
This feature has been included in release v0.11.0.

Out of curiosity, can you tell me what you were doing that required timed recordings?

**Comment by softuser25** [comment]
Nothing,just thought it would be a good idea,and from what i see none of the modules have time option.
