### ISSUE TITLE
keyboard.add_hotkey action only after all keys are released/re-pressed

### ISSUE THREAD

**Issue by chooper11** [boppreh/keyboard#91]
It appears all keys have to be released before a given hotkey can be activated again.

Would it work to change this so that a hotkey such as 'shift+q' only needs q to be un-pressed and re-pressed to activate the 'shift+q' hotkey a 2nd time?

What a cool project, thanks!

**Comment by boppreh** [comment]
Hi @chooper11 

That is indeed a big problem. Good news is that it should be fixed when the `suppress` branch is merged, since this is explicitly one of the test cases.

I'll keep this issue open to notify you when it's released.

Thank you for the report

**Comment by chooper11** [comment]
much appreciated!

**Comment by chooper11** [comment]
I have an update on the potential cause, in case it is somehow helpful... sounds like you might already know the reason from your above statements.

I wrote my own version of add_hotkey.  It uses only the keyboard.hook(callback) function, nothing else (I did my own keyboard mapping to figure out codes).  This cheap temporary version fixes the issue using a trigger key: a certain key out of the combination of keys is designated to execute the whole hotkey... so only that trigger key must be lifted now, before it can execute again.  I verified this with print commands to the console.

However, the problem is when i now attempt to use keyboard.send() inside of my version of add_hotkey, we're back to the same issue again: all keys must be released before the hotkey can execute again.  This might be a totally anticipated result based on what you wrote above... but it's as much as I understand at the moment so I thought I'd share.  Incidentally, is .send() executing on another thread?

Many thanks, wish I was good enough at python to help!

**Comment by boppreh** [comment]
The `suppress` branch that I'm working on behaves similarly to what you said: a trigger key that must be released. In fact that's how most hotkey systems work: to trigger <kbd>ctrl+a</kbd> you have to press <kbd>ctrl</kbd> **then** <kbd>a</kbd>, and that's the trigger key. The concept applies to trigger-on-release hotkeys too.

Unfortunately things get hazier when there are multiple non-modifier keys together, like <kbd>tab+backspace</kbd> or <kbd>a+b</kbd>. I'm not sure how often people use hotkeys like this.

>  Incidentally, is .send() executing on another thread?

`send()` is a blocking function that executes on the same thread that called it. This is true for both Windows and Linux.

**Comment by chooper11** [comment]
Boppreh,

Thanks again for your kind quick responses/explanations, I think I get it.  Incidentally, I'm definitely interested in using both a+b type and shift+ctrl+a type hotkeys, so that's at least one data point (both are working for me at the moment, so all good).

**Comment by boppreh** [comment]
Good data point, thanks. Are you using `suppress=True`for the <kbd>a+b</kbd> case?

**Comment by boppreh** [comment]
Took *much* longer than expected, but the `suppress` branch has been merged and v0.13.1 includes fixes for this and many other bugs. You can now hold <kbd>shift</kbd> and mash <kbd>q</kbd> as much as you want.

Modifiers are also treated differently, so holding <kbd>q</kbd>and mashing <kbd>shift</kbd> doesn't and shouldn't work, but <kbd>a+b</kbd> is ok in either order.

**Comment by chooper11** [comment]
awesome!
