### ISSUE TITLE
Should be 'event = None', not 'event_type = None'

### ISSUE THREAD

**Issue by ababak** [boppreh/keyboard#99]
https://github.com/boppreh/keyboard/blob/3c48358fc25a7891afbc94719e6c7edae431c155/keyboard/_nixmouse.py#L83

**Comment by boppreh** [comment]
Thank you, that was a stupid mistake. Please note the `mouse` package has been moved to https://github.com/boppreh/mouse, and is kept here only for backwards compatibility. I've also pushed a fix there.
